-- ====================================================================
-- MIGRATION: ATUALIZAÇÃO COMPLETA DA LISTA DE PROCEDIMENTOS DO SISTEMA
-- Zera a lista atual e insira os procedimentos por categoria: Consulta, Exame, Cirurgia
-- ====================================================================

-- 1. Garantir permissões de acesso
DROP POLICY IF EXISTS "Enable all access for consultas_procedimentos" ON public.consultas_procedimentos;
DROP POLICY IF EXISTS "Enable insert for all users" ON public.consultas_procedimentos;

CREATE POLICY "Enable all access for consultas_procedimentos" ON public.consultas_procedimentos
  FOR ALL USING (true) WITH CHECK (true);

-- 2. Zerar registros existentes (CASCADE para evitar erro de chaves estrangeiras)
TRUNCATE TABLE public.consultas_procedimentos CASCADE;

-- 3. Inserir a nova lista oficial de procedimentos
INSERT INTO public.consultas_procedimentos (code, name, type, status, recurso, total_quantity, available_quantity)
VALUES
-- ====================================================================
-- CATEGORIA: CONSULTAS
-- ====================================================================
('0001', 'ACOMPANHAMENTO E AVALIACAO DE GLAUCOMA POR FUNDOSCOPIA E TONOMETRIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0002', 'CONSULTA CARDIOPEDIÁTRICA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0003', 'CONSULTA EM CABEÇA E PESCOÇO', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0004', 'CONSULTA EM CARDIOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0005', 'CONSULTA EM CIRURGIA GERAL', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0006', 'CONSULTA EM DERMATOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0007', 'CONSULTA EM ENDOCRINOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0008', 'CONSULTA EM GASTROENTEROLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0009', 'CONSULTA EM GASTROENTEROLOGIA (CONSULTÓRIO)', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0010', 'CONSULTA EM HEMATOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0011', 'CONSULTA EM MASTOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0012', 'CONSULTA EM NEFROLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0013', 'CONSULTA EM NEUROCIRURGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0014', 'CONSULTA EM NEUROLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0015', 'CONSULTA EM NEUROLOGIA PARA AVALIAÇÃO DE TRATAMENTO COM TOXINA BOTULÍNICA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0016', 'CONSULTA EM NEUROLOGIA PEDIÁTRICA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0017', 'CONSULTA EM OFTALMOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0018', 'CONSULTA EM ORTOPEDIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0019', 'CONSULTA EM OTORRINOLARINGOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0020', 'CONSULTA EM PNEUMOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0021', 'CONSULTA EM PROCTOLOGIA TERC', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0022', 'CONSULTA EM PSIQUIATRIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0023', 'CONSULTA EM REUMATOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0024', 'CONSULTA EM UROLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0025', 'CONSULTA ESPECIALIZADA EM ANESTESIA GERAL', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0026', 'CONSULTA ESPECIALIZADA EM CIRURGIA DE MAMOPLASTIA REDUTORA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0027', 'CONSULTA ESPECIALIZADA EM CIRURGIA VASCULAR', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0028', 'CONSULTA ESPECIALIZADA EM NEUROLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0029', 'CONSULTA MÉDICA EM ATENÇÃO ESPECIALIZADA EM GINECOLOGIA E OBSTETRÍCIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0030', 'CONSULTA MÉDICA ESPECIALIZADA - MIGUILIM', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0031', 'CONSULTA OFTALMOLÓGICA ESPECIALIZADA EM CATARATA, RETINA, GLAUCOMA E PLÁSTICA OCULAR', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0032', 'CONSULTA OFTALMOLÓGICA ESPECIALIZADA EM CATARATA, RETINA, GLAUCOMA E PLÁSTICA OCULAR (PN)', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0033', 'CONSULTA P/ DIAGNOSTICO/ REAVALIACAO DE GLAUCOMA (01 ANO)', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0034', 'CONSULTA PRE CIRURGICA EM ANESTESIOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0035', 'CONSULTA PRE CIRURGICA EM CIRURGIA GERAL', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0036', 'CONSULTA PRE CIRURGICA EM CIRURGIA VASCULAR', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0037', 'CONSULTA PRE CIRURGICA EM COLOPROCTOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0038', 'CONSULTA PRE CIRURGICA EM GINECOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0039', 'CONSULTA PRE CIRURGICA EM MASTOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0040', 'CONSULTA PRE CIRURGICA EM ORTOPEDIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0041', 'CONSULTA PRE CIRURGICA EM OTORRINOLARINGOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0042', 'CONSULTA PRE CIRURGICA EM UROLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0043', 'CONSULTA PRE-CIRÚRGICA EM NEUROCIRURGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0044', 'CONSULTA RETORNO COM REALIZAÇÃO DE RAIO-X', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),

-- ====================================================================
-- CATEGORIA: EXAMES
-- ====================================================================
('0045', 'ANATOMO - BIOPSIA EM PECA CIRURGICA SIMPLES OU PELE', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0046', 'ANGIORESSONÂNCIA 1 SEGMENTO: COXA OU PERNA; BRAÇO OU ANTEBRAÇO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0047', 'ANGIORESSONÂNCIA 2 SEGMENTOS: COXA E PERNA; BRAÇO E ANTEBRAÇO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0048', 'ANGIORESSONÂNCIA ARTERIAL DO CRÂNIO COM 1 SEGMENTO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0049', 'ANGIORESSONÂNCIA ARTERIAL DO CRÂNIO COM 1 SEGMENTO (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0050', 'ANGIORESSONÂNCIA ARTERIAL DO CRÂNIO COM 1 SEGMENTO (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0051', 'ANGIORESSONÂNCIA ARTERIAL DO CRÂNIO COM 2 SEGMENTOS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0052', 'ANGIORESSONÂNCIA ARTERIAL DO PESCOÇO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0053', 'ANGIORESSONÂNCIA DA AORTA ABDOMINAL COM 1 SEGMENTO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0054', 'ANGIORESSONÂNCIA DA AORTA ABDOMINAL COM 2 SEGMENTOS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0055', 'ANGIORESSONÂNCIA DE AORTA TORÁCICA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0056', 'ANGIORESSONÂNCIA DO TÓRAX', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0057', 'ANGIORESSONÂNCIA SACRO ILÍACAS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0058', 'ANGIORESSONÂNCIA UNILATERAL ARTERIAL OU VENOSA DE MEMBRO INFERIOR (1 SEGMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0059', 'ANGIORESSONÂNCIA UNILATERAL ARTERIAL OU VENOSA DE MEMBRO SUPERIOR (1 SEGMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0060', 'ANGIORESSONÂNCIA VENOSA DO CRÂNIO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0061', 'ANGIORESSONÂNCIA VENOSA DO CRÂNIO (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0062', 'ANGIORESSONÂNCIA VENOSA DO CRÂNIO (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0063', 'ANGIORESSONÂNCIA VENOSA DO PESCOÇO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0064', 'ANGIOTOMOGRAFIA ARTERIAL DA PELVE', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0065', 'ANGIOTOMOGRAFIA ARTERIAL DE ABDOMEN SUPERIOR', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0066', 'ANGIOTOMOGRAFIA ARTERIAL DE PESCOÇO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0067', 'ANGIOTOMOGRAFIA ARTERIAL DO CRÂNIO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0068', 'ANGIOTOMOGRAFIA ARTERIAL DO TÓRAX', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0069', 'ANGIOTOMOGRAFIA DA BASE DO CRÂNIO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0070', 'ANGIOTOMOGRAFIA DA PORTA-ESPLÊNICA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0071', 'ANGIOTOMOGRAFIA DE ABDOMEN ( AORTA ABDOMINAL)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0072', 'ANGIOTOMOGRAFIA DE AORTA ABDOMINAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0073', 'ANGIOTOMOGRAFIA DE AORTA TORÁCICA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0074', 'ANGIOTOMOGRAFIA DE AORTA TÓRACO-ABDOMINAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0075', 'ANGIOTOMOGRAFIA DE ARTÉRIAS MESENTÉRICAS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0076', 'ANGIOTOMOGRAFIA DE ARTÉRIAS RENAIS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0077', 'ANGIOTOMOGRAFIA DE CARÓTIDAS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0078', 'ANGIOTOMOGRAFIA DE CORONÁRIAS COM CONTRASTE', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0079', 'ANGIOTOMOGRAFIA DE MEMBROS INFERIORES', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0080', 'ANGIOTOMOGRAFIA DE SEGMENTO APENDICULAR (COXA OU PERNA)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0081', 'ANGIOTOMOGRAFIA DO TÓRAX (TEP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0082', 'ANGIOTOMOGRAFIA DOS MEMBROS SUPERIORES', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0083', 'ANGIOTOMOGRAFIA DOS VASOS INTRAC. DA BASE', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0084', 'ANGIOTOMOGRAFIA VENOSA DA PELVE', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0085', 'ANGIOTOMOGRAFIA VENOSA DE ABDOMEN SUPERIOR', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0086', 'ANGIOTOMOGRAFIA VENOSA DO CRÂNIO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0087', 'ANGIOTOMOGRAFIA VENOSA DO PESCOÇO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0088', 'ANGIOTOMOGRAFIA VENOSA DO TÓRAX', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0089', 'ANUSCOPIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0090', 'AUDIOMETRIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0091', 'AVALIAÇÃO URODINÂMICA COMPLETA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0092', 'BIOMETRIA ULTRASSÔNICA MONOCULAR', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0093', 'BIOMICROSCOPIA DE FUNDO DE OLHO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0094', 'BIOPSIA EM LAMINAS DE PAAF ATÉ 5 EXAMES', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0095', 'BIOPSIA EM MARGENS DE LESOES DE PELE E PEQUENOS TUMORES', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0096', 'BIOPSIA EM PECA CIRURGICA SIMPLES OU PELE', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0097', 'BIOPSIA SIMPLES POR LESAO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0098', 'BIOPSIA SIMPLES POR LESÃO - ANTRO E CORPO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0099', 'BIÓPSIA DE CONJUNTIVA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0100', 'BIÓPSIA DE PÁLPEBRA (INCISIONAL)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0101', 'BIÓPSIA DE PÁLPEBRA (INCISIONAL) - PN', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0102', 'BIÓPSIA INCISIONAL DE MAMA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0103', 'CAMPIMETRIA COMPUTADORIZADA - CAMPO VISUAL (CVC) - PN', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0104', 'CAMPIMETRIA COMPUTADORIZADA COM EMISSÃO DE LAUDO - CISAMAPI', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0105', 'CERATOMETRIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0106', 'COLONOSCOPIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0107', 'COLONOSCOPIA (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0108', 'COLONOSCOPIA (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0109', 'DENSITOMETRIA OSSEA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0110', 'DUPPLEX SCAN 1 MEMBRO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0111', 'DUPPLEX SCAN 2 MEMBROS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0112', 'DUPPLEX SCAN DE ARTÉRIAS CERVICAIS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0113', 'DUPPLEX SCAN DE ARTÉRIAS ILÍACAS BILATERAIS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0114', 'DUPPLEX SCAN DE ARTÉRIAS RENAIS (REAJUSTADO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0115', 'DUPPLEX SCAN DE CARÓTIDAS E VERTEBRAIS (REAJUSTADO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0116', 'DUPPLEX SCAN DE VIAS SUBCLÁVICAS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0117', 'ECOCARDIOGRAFIA BI-DIMENSIONAL COM OU SEM DOPLLER', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0118', 'ECOCARDIOGRAFIA COM OU SEM DOPLLER (REAJUSTADO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0119', 'ECOCARDIOGRAMA FETAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0120', 'ECOCARDIOGRAMA TRANSESOFAGICO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0121', 'ELETROENCEFALOGRAMA (LAUDO À DISTÂNCIA)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0122', 'ELETRONEUROMIOGRAMA (1 OU 2 MEMBROS) (REAJUSTADO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0123', 'ENDOSCOPIA DIGESTIVA ALTA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0124', 'ENDOSCOPIA DIGESTIVA ALTA (ABRE CAMPO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0125', 'ENDOSCOPIA DIGESTIVA ALTA (CISAMAPI PONTE NOVA)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0126', 'ESPIROMETRIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0127', 'GONIOSCOPIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0128', 'LOGOAUDIOMETRIA (LDV- IRF -LRF)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0129', 'MAMOGRAFIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0130', 'MICROSCOPIA ESPECULAR DE CORNEA - PN', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0131', 'MICROSCOPIA ESPECULAR DE CÓRNEA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0132', 'POLISSONOGRAFIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0133', 'POLISSONOGRAFIA (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0134', 'POLISSONOGRAFIA (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0135', 'POLISSONOGRAFIA DO SONO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0136', 'RETINOGRAFIA BINOCULAR (GLAUCOMA)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0137', 'RETINOGRAFIA BINOCULAR (GLAUCOMA) (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0138', 'RETINOGRAFIA BINOCULAR (GLAUCOMA) (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0139', 'RETINOGRAFIA COLORIDA BINOCULAR', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0140', 'RETINOGRAFIA COLORIDA BINOCULAR - PN', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0141', 'RETINOGRAFIA FLUORESCENTE BINOCULAR (ANGIOFLUORECÊNCIA)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0142', 'RETINOGRAFIA FLUORESCENTE BINOCULAR (ANGIOFLUORECÊNCIA) - PN', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0143', 'RETINOGRAFIA FLUORESCENTE BINOCULAR (ANGIOFLUORECÊNCIA) - PN (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0144', 'RETINOGRAFIA FLUORESCENTE BINOCULAR (ANGIOFLUORECÊNCIA) - PN (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),

-- ====================================================================
-- CATEGORIA: CIRURGIAS E PROCEDIMENTOS INVASIVOS/TERAPÊUTICOS
-- ====================================================================
('0145', 'ABSCESSO ANORRETAL - DRENAGEM', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0146', 'ADENO-AMIGDALECTOMIA X 2 + CORNETO INFERIOR - CAUTERIZAÇÃO LINEAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0147', 'ADENO-AMIGDALECTOMIA X 2 + CORNETO INFERIOR - CAUTERIZAÇÃO LINEAR - UNILATERAL X2 +TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL X2', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0148', 'ADENOIDECTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0149', 'AMIGDALECTOMIA C/ ADENOIDECTOMIA (COM OU SEM TURBINOPLASTIA)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0150', 'ANGIOPLASTIA CORONARIANA C/ IMPLANTE DE DOIS STENTS - 01 DIÁRIA ENF.', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0151', 'ANGIOPLASTIA CORONARIANA COM IMPLANTE DE STENT - 01 DIÁRIA ENF.', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0152', 'ANGIOPLASTIA CORONARIANA PRIMARIA-INCLUINDO 01 DIÁRIA ENF', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0153', 'ANGIOPLASTIA CORONARIANA SEM STENT - 01 DIÁRIA ENF.', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0154', 'APENDICECTOMIA POR VIDEOLAPAROSCOPIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0155', 'APLICAÇÃO DE TOXINA BOTULÍNICA (NEUROLOGIA) SEM O MEDICAMENTO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0156', 'APLICAÇÃO DE TOXINA BOTULÍNICA FACIAL - C/ PRODUTO - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0157', 'APLICAÇÃO DE TOXINA BOTULÍNICA FACIAL - INCLUINDO O PRODUTO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0158', 'ARTRODESE AO NÍVEL DO TORNOZELO - TRATAMENTO CIRÚRGICO + PÉ PLANO/ PÉ CAVO/ COALISÃO TARSAL - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0159', 'ARTRODESE DE PUNHO + ENXERTO ÓSSEO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0160', 'ARTROPLASTIA TOTAL DE JOELHO COM IMPLANTES - TRATAMENTO CIRÚRGICO PROTESE NACIONAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0161', 'ARTROPLASTIA TOTAL DE JOELHO COM IMPLANTES - TRATAMENTO CIRÚRGICO PRÓTESE IMPORTADA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0162', 'ARTROPLASTIA TOTAL DO QUADRIL PROTESE IMPORTADA CIMENTADA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0163', 'ARTROPLASTIA TOTAL DO QUADRIL PROTESE IMPORTADA SEM CIMENTO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0164', 'ARTROPLASTIA TOTAL DO QUADRIL PROTESE NACIONAL CIMENTADA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0165', 'ARTROPLASTIA TOTAL DO QUADRIL PROTESE NACIONAL SEM CIMENTO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0166', 'AUTOTRANSPLANTE CONJUNTIVAL OU RECOBRIMENTO CONJUNTIVAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0167', 'AUTOTRANSPLANTE CONJUNTIVAL OU RECOBRIMENTO CONJUNTIVAL - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0168', 'BIOPSIA PERCUTÂNEA DE FRAGMENTO MAMÁRIO (CORE BIOPSY) ORIENTADA POR USG OU RX-AGULHA GROSSA (REAJUSTADO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0169', 'BLEFAROPLASTIA SUPERIOR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0170', 'BÓCIO MERGULHANTE: EXTIRPAÇÃO POR ACESSO CÉRVICO-TORÁCICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0171', 'CANTOPLASTIA LATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0172', 'CANTOPLASTIA MEDIAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0173', 'CANTOPLASTIA MEDIAL - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0174', 'CAPSULECTOMIA POSTERIOR CIRURGICA POR VITRÓFAGO - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0175', 'CAPSULECTOMIA POSTERIOR CIRÚRGICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0176', 'CAPSULECTOMIA POSTERIOR CIRÚRGICA POR VITREOFAGO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0177', 'CAPSULOTOMIA A YAG LASER (CADA OLHO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0178', 'CAPSULOTOMIA A YAG LASER (CADA OLHO) (COMPLEMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0179', 'CAPSULOTOMIA A YAG LASER (CADA OLHO) (SIGTAP)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0180', 'CAPSULOTOMIA MONOCULAR LASER - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0181', 'CATETERISMO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0182', 'CIRURGIA BARIÁTRICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0183', 'CIRURGIA ESTERILIZADORA MASCULINA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0184', 'CISTO SACRO-COCCÍGEO - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0185', 'CISTO SINOVIAL - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0186', 'COLANGIOPANCREATOGRAFIA RETRÓGRADA ENDOSCÓPICA + PAPILOTOMIA ENDOSCÓPICA (PARA RETIRADA DE CÁLCULOS COLEDOCIANOS OU DRENAGEM BILIAR)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0187', 'COLECISTECTOMIA COM COLANGIOGRAFIA POR VIDEOLAPAROSCOPIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0188', 'COLECISTECTOMIA SEM COLANGIOGRAFIA POR VIDEOLAPAROSCOPIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0189', 'COLOCAÇÃO CIRÚRGICA DE DUPLO J UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0190', 'COLOCAÇÃO URETEROSCÓPICA DE DUPLO J UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0191', 'COLONOSCOPIA COM MUCOSECTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0192', 'COLONOSCOPIA COM MUCOSECTOMIA E HESMOSTASIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0193', 'COLONOSCOPIA COM POLPECTOMIA COM PÓLIPO PEDICULADO DE GRANDE DIMENSÃO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0194', 'CORREÇÃO CIRÚRGICA DE EPICANTO E TELECANTO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0195', 'CORREÇÃO CIRÚRGICA DE HERNIA DE IRIS- PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0196', 'CORREÇÃO CIRÚRGICA DE HÉRNIA DE ÍRIS', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0197', 'CORREÇÃO CIRÚRGICA DE LAGOFTALMO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0198', 'CORREÇÃO CIRÚRGICA DE LAGOFTALMO-PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0199', 'CORREÇÃO DE ENTRÓPIO E ECTRÓPIO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0200', 'CORREÇÃO DE ENTRÓPIO E ECTRÓPIO - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0201', 'CORREÇÃO DE INVERSÃO PAPILAR - UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0202', 'CRIOTERAPIA OCULAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0203', 'CRIOTERAPIA OCULAR - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0204', 'DACRIOCISTORRINOSTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0205', 'DACRIOCISTORRINOSTOMIA - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0206', 'DESCOMPRESSÃO MEDULAR E/OU CAUDA EQUINA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0207', 'DOENÇA DE PEYRONIE - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0208', 'DRENAGEM DE ABSCESSO DE MAMA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0209', 'DRENAGEM DE ABSCESSO DE PALPEBRA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0210', 'ENDOMETRIOSE PERITONEAL - TRATAMENTO CIRÚRGICO VIA LAPAROSCÓPICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0211', 'ENUCLEAÇÃO DE GLOBO OCULAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0212', 'EPIDIDIMECTOMIA UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0213', 'EPILAÇÃO A LASER', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0214', 'EPILAÇÃO A LASER - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0215', 'EPILAÇÃO DE CÍLIOS', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0216', 'EPILAÇÃO DE CÍLIOS - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0217', 'ESCLEROTERAPIA KIYOMITSU', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0218', 'EVISCERAÇÃO DE GLOBO OCULAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0219', 'EXCISAO E SUTURA DE LESAO NA PELE C/ PLASTICA EM Z OU ROTACAO DE RETALHO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0220', 'EXERESE DE CALAZIO E OUTRAS PEQUENAS LESOES DA PALPEBRA E SUPERCILIOS - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0221', 'EXÉRESE DE CALÁZIO E OUTRAS PEQUENAS LESÕES DA PÁLPEBRA E SUPERCÍLIOS', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0222', 'EXÉRESE DE CISTO VAGINAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0223', 'EXÉRESE DE LESÃO DA MAMA POR MARCAÇÃO ESTEREOTÁXICA OU ROLL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0224', 'EXÉRESE DE MAMA SUPRA-NUMERÁRIA - UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0225', 'EXÉRESE DE NÓDULO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0226', 'EXÉRESE DE TUMOR DE CONJUNTIVA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0227', 'EXÉRESE DE TUMOR DE CONJUNTIVAL (PN)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0228', 'EXÉRESE DE TUMOR DE PÁLPEBRA - RESSECÇÃO DE TUMOR PALPEBRAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0229', 'EXÉRESE DE TUMOR DE PÁLPEBRA - RESSECÇÃO DE TUMOR PALPEBRAL - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0230', 'EXPLANTE DE LENTE INTRA-OCULAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0231', 'EXPLANTE DE LENTE INTRA-OCULAR - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0232', 'EXPLORAÇÃO/DESCOMPRESSÃO TOTAL/PARCIAL DO NERVO FACIAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0233', 'FACOEMULSIFICACAO COM IMPLANTE DE LENTE INTRA-OCULAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0234', 'FACOEMULSIFICACAO COM IMPLANTE DE LENTE INTRA-OCULAR DOBRAVEL INCLUINDO CONSULTA PRÉ E PÓS CIRURGICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0235', 'FACOEMULSIFICAÇÃO COM IMPLANTE DE LENTE INTRA OCULAR DOBRAVEL - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0236', 'FISSURECTOMIA COM OU SEM ESFINCTEROTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0237', 'FISTULECTOMIA ANORRETAL COM ABAIXAMENTO MUCOSO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0238', 'FISTULECTOMIA DE MAMA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0239', 'FOTOCOAGULAÇÃO A LASER', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0240', 'FOTOCOAGULAÇÃO A LASER - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0241', 'FOTOTRABECULOPLASTIA A LASER', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0242', 'FOTOTRABECULOPLASTIA MONUCULAR A LASER - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0243', 'FRATURA E OU LUXAÇÕES (INCLUINDO DESLOCAMENTO EPIFISÁRIO COTOVELO - PUNHO - TRATAMENTO CIRÚRGICO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0244', 'FRENOTOMIA LINGUAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0245', 'GASTROPLASTIA PARA OBESIDADE MÓRBIDA POR VIDEOLAPAROSCOPIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0246', 'GINECOMASTIA - UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0247', 'HALLUX VALGUS (UM PÉ) - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0248', 'HEMORRÓIDAS - LIGADURA ELÁSTICA (POR SESSÃO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0249', 'HERNIORRAFIA INGUINAL - BILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0250', 'HERNIORRAFIA INGUINAL ENCARCERADA - BILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0251', 'HERNIORRAFIA INGUINAL NO RN OU LACTENTE', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0252', 'HERNIORRAFIA RECIDIVANTE', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0253', 'HERNIORRAFIA SEM RESSECÇÃO INTESTINAL ENCARCERADA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0254', 'HIPOSPADIA - POR ESTÁGIO - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0255', 'HIPOSPADIA DISTAL - TRATAMENTO EM 1 TEMPO - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0256', 'HISTERECTOMIATOTAL LAPAROSCÓPICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0257', 'HISTEROSCOPIA CIRÚRGICA COM BIÓPSIA E/OU CURETAGEM UTERINA, LISE DE SINÉQUIAS, RETIRADA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0258', 'HISTEROSCOPIA COM RESSECTOSCÓPIO PARA MIOMECTOMIA, POLIPECTOMIA, METROPLASTIA, END', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0259', 'HÉRNIA DE DISCO TÓRACO-LOMBAR - TRATAMENTO CIRURGICO + DESCOMPRESSÃO MEDULAR E/OU CAUDA EQUINA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0260', 'IMPLANTE SECUNDARIO DE LENTE INTRA-OCULAR - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0261', 'IMPLANTE SECUNDÁRIO DE LENTE INTRA-OCULAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0262', 'INFILTRAÇÃO SUBCONJUNTIVAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0263', 'INJECAO INTRAVITREO DE OZOURDEX - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0264', 'INJEÇÃO ANTIANGIOGÊNICA DE TRIANCINOLONA (INCLUI MEDICAMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0265', 'INJEÇÃO DE GÁS INTRA-OCULAR (SF6 OU C3F8)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0266', 'INJEÇÃO INTRAVÍTREA (SEM A MEDICAÇÃO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0267', 'INJEÇÃO INTRAVÍTREA (SEM A MEDICAÇÃO) - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0268', 'INJEÇÃO MONOCULAR ANTIANGIOGÊNICA DE AVASTIN (INCLUI MEDICAMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0269', 'INJEÇÃO MONOCULAR ANTIANGIOGÊNICA DE AVASTIN (INCLUI MEDICAMENTO) - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0270', 'INJEÇÃO MONOCULAR ANTIANGIOGÊNICA DE EYLIA (INCLUI MEDICAMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0271', 'INJEÇÃO MONOCULAR ANTIANGIOGÊNICA DE EYLIA (INCLUI MEDICAMENTO) - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0272', 'INJEÇÃO MONOCULAR ANTIANGIOGÊNICA DE LUCENTIS (INCLUI MEDICAMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0273', 'INJEÇÃO MONOCULAR ANTIANGIOGÊNICA DE LUCENTIS (INCLUI MEDICAMENTO) - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0274', 'INJEÇÃO MONOCULAR INTRAVÍTREA (MEDICAÇÃO COM O PACIENTE)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0275', 'INJEÇÃO MONOCULAR INTRAVÍTREA DE OZURDEX (INCLUI MEDICAMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0276', 'IRIDECTOMIA A YAG LASER (CADA OLHO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0277', 'IRIDECTOMIA CIRURGICA - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0278', 'IRIDOTOMIA A YAG LASER (CADA OLHO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0279', 'IRIDOTOMIA MONOCULAR LASER - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0280', 'IRODOTOMIA LASER MONOCULAR (PONTE NOVA)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0281', 'LAPAROSCOPIA GINECOLÓGICA COM OU SEM BIÓPSIA (INCLUI A CROMOTUBAGEM)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0282', 'LESÃO ANAL - ELETROCAUTERIZAÇÃO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0283', 'LINFADENECTOMIA AXILAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0284', 'MAMOPLASTIA REDUTORA SEM SILICONE', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0285', 'MANIPULAÇÃO ARTICULAR SOB ANESTESIA GERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0286', 'MASTECTOMIA RADICAL OU RADICAL MODIFICADA - QUALQUER TÉCNICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0287', 'MASTECTOMIA SIMPLES', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0288', 'MASTECTOMIA SUBCUTÂNEA E INCLUSÃO DA PRÓTESE', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0289', 'MASTOIDECTOMIA: TIMPANOMASTOIDECTOMIA+EXPLORAÇÃO E DESCOMPRESSÃODO NERVO FACIAL+ESTENOSE CONDUTO AUDITIVO EXTERNO (CANALPLASTIA)+ RESSECÇÃO DO OSSO TEMPORAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0290', 'MASTOPLASTIA EM MAMA OPOSTA APÓS RECONSTRUÇÃO DA CONTRALATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0291', 'MENISCECTOMIA - UM MENISCO - PROCEDIMENTO VIDEOARTROSCÓPICO DE JOELHO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0292', 'MICRONEURÓLISE MÚLTIPLAS', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0293', 'MIOMECTOMIA UTERINA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0294', 'NEFRECTOMIA RADICAL LAPAROSCÓPICA UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0295', 'NEFROLITOTRIPSIA PERCUTÂNEA UNILATERAL (MEC., E.H., OU US)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0296', 'NEFROLITOTRIPSIA PERCUTÂNEA UNILATERAL (MEC., E.H., OU US) + URETERORRENOLITOTRIPSIA FLEXÍVEL A LASER UNILATERAL + COLOCAÇÃO URETEROSCÓPICA DE DUPLO J - UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0297', 'NEFROLITOTRIPSIA PERCUTÂNEA UNILATERAL (PNEUMÁTICO-BALÍSTICA - MEC., ELETROHIDRÁULICA - E.H., OU ULTRASSOM - US) + URETERORRENOLITOTRIPSIA FLEXÍVEL A LASER UNILATERAL + COLOCAÇÃO URETEROSCÓPICA DE DUP', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0298', 'NEFROLITOTRIPSIA PERCUTÂNEA UNILATERAL(MEC.,E.H., OU US) + COLOCAÇÃO URETEROSCÓPICA DE DUPLO J - UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0299', 'OOFORECTOMIA LAPAROSCÓPICA UNI OU BILATERAL OU OOFOROPLASTIA UNI OU BILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0300', 'OOFRECTOMIA/ OOFOROPLASTIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0301', 'OPME P/ANGIOPLASTIA COM IMPLANTE DE DOIS STENT', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0302', 'OPME P/ANGIOPLASTIA COM IMPLANTE DE STENT', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0303', 'OPME P/ANGIOPLASTIA CORONARIANA PRIMÁRIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0304', 'OPME P/ANGIOPLASTIA SEM IMPLANTE DE STENT', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0305', 'ORBITOTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0306', 'ORQUIECTOMIA UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0307', 'PAAF DE MAMA - PUNÇÃO ASPIRATIVA DE MAMA POR AGULHA FINA (GUIADA POR ULTRASSONOGRAFIA)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0308', 'PAAF DE MAMA - PUNÇÃO ASPIRATIVA DE MAMA POR AGULHA FINA (GUIADA POR ULTRASSONOGRAFIA) (COMPLEMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0309', 'PAAF DE MAMA - PUNÇÃO ASPIRATIVA DE MAMA POR AGULHA FINA (GUIADA POR ULTRASSONOGRAFIA) (SIGTAP)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0310', 'PAAF TIREÓIDE - PUNÇÃO OU BIÓPSIA PERCUTANIA POR AGULHA FINA DA TIREÓIDE (GUIADA POR ULTRASSONOGRAFIA)(REAJUSTADO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0311', 'PAAF TIREÓIDE - PUNÇÃO OU BIÓPSIA PERCUTANIA POR AGULHA FINA DA TIREÓIDE (GUIADA POR ULTRASSONOGRAFIA)(REAJUSTADO) (COMPLEMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0312', 'PAAF TIREÓIDE - PUNÇÃO OU BIÓPSIA PERCUTANIA POR AGULHA FINA DA TIREÓIDE (GUIADA POR ULTRASSONOGRAFIA)(REAJUSTADO) (SIGTAP)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0313', 'PARTO IHNSD', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0314', 'PIELOPLASTIA LAPAROSCÓPICA UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0315', 'PLASTICA MAMARIA FEMININA NÃO ESTETICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0316', 'PLÁSTICA DE CONJUNTIVA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0317', 'PLÁSTICA DE CONJUNTIVA PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0318', 'POLIPECTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0319', 'PROSTATAVESICULECTOMIA RADICAL + LINFADENECTOMIA PÉLVICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0320', 'PROSTATAVESICULECTOMIA RADICAL LAPAROSCÓPICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0321', 'PROSTATAVESICULECTOMIA RADICAL LAPAROSCÓPICA + LINFADENECTOMIA PÉLVICA LAPAROSCÓPICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0322', 'PROSTATECTOMIA A CÉU ABERTO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0323', 'PROSTATECTOMIA A CÉU ABERTO + TUMOR VESICAL - RESSECÇÃO ENDOSCÓPICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0324', 'PÉ PLANO/ PÉ CAVO/ COALISÃO TARSAL - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0325', 'PÉ TORTO CONGÊNITO (UM PÉ) - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0326', 'PUNÇÃO LOMBAR COM ANALISE DE LIQUOR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0327', 'PUNÇÃO LOMBAR COM PRESSÃO DE ABERTURA E ANALISE DE LIQUOR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0328', 'PUNÇÃO PARA BIOPSIA/ASPIRATIVA DE ORGÃO OU ESTRUTURA ORIENTADA POR RX, US, CT (BIOPSIA FIGADO, RIM)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0329', 'QUADRANTECTOMIA - RESSECÇÃO SEGMENTAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0330', 'QUADRANTECTOMIA E LINFADENECTOMIA AXILAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0331', 'RECONSTITUIÇÃO DE CANAL LACRIMAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0332', 'RECONSTITUIÇÃO DE CAVIDADE ORBITÁRIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0333', 'RECONSTITUIÇÃO DE FUNDO DE SACO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0334', 'RECONSTITUIÇÃO PARCIAL DE PÁLPEBRA COM TARSORRAFIA OU BLEFARORRAFIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0335', 'RECONSTITUIÇÃO TOTAL DE PÁLPEBRA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0336', 'RECONSTRUÇÃO DA MAMA COM PRÓTESE E/OU EXPANSOR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0337', 'RECONSTRUÇÃO DE CÂMARA ANTERIOR DO OLHO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0338', 'RECONSTRUÇÃO, RETENCIONAMENTO OU REFORÇO DO LIGAMENTO CRUZADO ANTERIOR OU POSTERIOR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0339', 'RECONSTRUÇÃO, RETENCIONAMENTO OU REFORÇODO LIGAMENTO CRUZADO ANTERIOR OU POSTERIOR (PROCEDIMENTO VIDEOARTROSCÓPICO DE JOELHO) + REPARO OU SUTURA DE UM MENISCO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0340', 'REFLUXO GASTROESOFÁGICO-TRAT CIRÚRGICO(HERNIA DE HIATO)P/ VIDEOLAPAROSCOPIA+COLECISTECTOMIA SEM COLLANGIOGRAFIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0341', 'REMOÇÃO DE ÓLEO DE SILICONE', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0342', 'REMOÇÃO DE ÓLEO DE SILICONE - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0343', 'REPARO OU SUTURA DE UM MENISCO - PROCEDIMENTO VIDEOARTROSCÓPICO DE JOELHO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0344', 'REPARO OU SUTURA DE UM MENISCO (PROCEDIMENTO VIDEOARTROSCÓPICO DE JOELHO) + CONDROPLASTIA (COM REMOÇÃO DE CORPOS LIVRES) (PROCEDIMENTO VIDEOARTROSCÓPICO DE JOELHO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0345', 'REPOSICIONAMENTO DE LENTE INTRA-OCULAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0346', 'REPOSICIONAMENTO DE LENTE INTRA-OCULAR (PONTE NOVA)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0347', 'RESSECÇÃO DO LINFONODO SENTINELA/ TORÁCICA LATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0348', 'RESSECÇÃO DOS DUCTOS PRINCIPAIS DA MAMA - UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0349', 'RESSECÇÃO ENDOSCÓPICA DA PRÓSTATA + URETROTOMIA INTERNA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0350', 'RETINOPEXIA COM INTROFLEXÃO ESCLERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0351', 'RETINOPEXIA COM INTROFLEXÃO ESCLERAL (PONTE NOVA)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0352', 'RETIRADA DE CORPO ESTRANHO DA CÓRNEA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0353', 'RETIRADA ENDOSCÓPICA DE CÁLCULO DE URETER UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0354', 'RETIRADA ENDOSCÓPICA DE DUPLO J', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0355', 'RETRAÇÃO PALPEBRAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0356', 'RINOSSEPTOPLASTIA FUNCIONAL + TURBINECTOMIA OU TURBINOPLASTIA - BILATERAL + CORNETO INFERIOR - CAUTERIZAÇÃO LINEAR - BILATERAL + SINUSECTOMIA MAXILAR - VIA ENDONASAL X 2 + ETMOIDECTOMIAINTRANASAL X 2', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0357', 'RINOSSEPTOPLASTIA FUNCIONAL + TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL + CORNETO INFERIOR - CAUTERIZAÇÃO LINEAR- UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0358', 'RINOSSEPTOPLASTIA FUNCIONAL + TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL X 2 + CORNETO INFERIOR - CAUTERIZAÇÃO LINEAR- UNILATERAL X 2 + ADENO-AMIGDALECTOMIA X 2', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0359', 'RIZOTOMIA PERCUTÂNEA POR SEGMENTO - QUALQUER MÉTODO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0360', 'RUPTURA DO MANGUITO ROTADOR - PROCEDIMENTO VIDEOARTROSCÓPICO DE OMBRO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0361', 'RUPTURA DO MANGUITO ROTADOR (PROCEDIMENTO VIDEOARTROSCÓPICO DE OMBRO) + SINOVECTOMIA TOTAL (PROCEDIMENTO VIDEOARTROSCÓPICO DE OMBRO) + + TENOTOMIA DA PORÇÃO LONGA DOBÍCEPS (PROCEDIMENTO VIDEOARTROSCÓP', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0362', 'SALPINGECTOMIA UNI OU BILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0363', 'SEPTOPLASTIA (COM TURBINOPLASTIA)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0364', 'SEPTOPLASTIA PARA CORREÇÃO DE DESVIO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0365', 'SETORECTOMIA / QUADRANTECTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0366', 'SIMBLEFAROPLASTIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0367', 'SIMBLEFAROPLASTIA (PONTE NOVA)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0368', 'SINEQUIOTOMIA CIRÚRGICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0369', 'SINUSECTOMIA MAXILAR - VIA ENDONASAL X 2 + ETMOIDECTOMIA INTRANASAL X 2+ SINUSOTOMIA ESFENOIDAL X 2 SINUSOTOMIA FRONTAL INTRANASAL POR VIDEOENDOSCOPIA X2', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0370', 'SINUSOTOMIA BILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0371', 'SINUSOTOMIA ESFENOIDAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0372', 'SINUSOTOMIA TRANSMAXILAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0373', 'SONDAGEM DE VIAS LACRIMAIS', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0374', 'SONDAGEM DE VIAS LACRIMAIS - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0375', 'SUTURA DE CONJUNTIVA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0376', 'SUTURA DE CÓRNEA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0377', 'SUTURA DE ESCLERA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0378', 'SUTURA DE PÁLPEBRAS', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0379', 'TENOPLASTIA / ENXERTO DE TENDÃO - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0380', 'TENOPLASTIA / ENXERTO DE TENDÃO - TRATAMENTO CIRÚRGICO + TRANSPOSIÇÃO ÚNICA DE TENDÃO + OSTEOTOMIA OU PSEUDARTROSE DO TARSO E MÉDIO PÉ - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0381', 'TENÓLISE/TENDONESE - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0382', 'TIMPANOPLASTIA (UNI / BILATERAL)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0383', 'TIMPANOPLASTIA: TIMPANOPLASTIA COM RECONSTRUÇÃO DE CADEIA OSSICULAR + ESTENOSE CONDUTO AUDITIVO EXTERNO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0384', 'TIMPANOTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0385', 'TIREOIDECTOMIA PARCIAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0386', 'TRABECULECTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0387', 'TRABECULECTOMIA - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0388', 'TRABECULECTOMIA - PN (COMPLEMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0389', 'TRABECULECTOMIA - PN (SIGTAP)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0390', 'TRAQUELECTOMIA - AMPUTAÇÃO, CONIZAÇÃO - (COM OU SEM CIRURGIA DE ALTA FREQUÊNCIA / CAF)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0391', 'TRATAMENTO CIRURGICO DE PTERIGIO - EXERESE DE PTERIGIO - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0392', 'TRATAMENTO CIRURGICO DE PTERIGIO - EXERESE DE PTERIGIO - PN (COMPLEMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0393', 'TRATAMENTO CIRURGICO DE PTERIGIO - EXERESE DE PTERIGIO - PN (SIGTAP)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0394', 'TRATAMENTO CIRURGICO DE XANTELASMA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0395', 'TRATAMENTO CIRÚRGICO DE PTERÍGIO - EXERESE DE PTERÍGIO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0396', 'TRATAMENTO CIRÚRGICO DE PTERÍGIO - EXERESE DE PTERÍGIO (COMPLEMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0397', 'TRATAMENTO CIRÚRGICO DE PTERÍGIO - EXERESE DE PTERÍGIO (SIGTAP)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0398', 'TRATAMENTO CIRÚRGICO DE RETOCELE (COLPOPERINEOPLASTIA POSTERIOR)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0399', 'TRATAMENTO CIRÚRGICO DE ROTURA DO MENISCO COM MENISCECTOMIA PARCIAL/ TOTAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0400', 'TRATAMENTO CIRÚRGICO DE TRÍQUIASE ( PN) COM OU SEM ENXERTO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0401', 'TRATAMENTO CIRÚRGICO DE TRÍQUIASE COM OU SEM ENXERTO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0402', 'TRATAMENTO DA SÍNDROME COMPRESSIVA EM TÚNEL OSTEO-FIBROSO AO NÍVEL DO CARPO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0403', 'TRATAMENTO DE NECROSE AVASCULAR POR FORAGEM DE ESTAQUEAMENTO ASSOCIADA À NECROSE', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0404', 'TRATAMENTO DE PTOSE PALPEBRAL - CORREÇÃO DE PTOSE PALPEBRAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0405', 'TRATAMENTO DE PTOSE PALPEBRAL PN- CORREÇÃO DE PTOSE PALPEBRAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0406', 'TRATAMENTO DE PTOSE PALPEBRAL PN- CORREÇÃO DE PTOSE PALPEBRAL (COMPLEMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0407', 'TRATAMENTO DE PTOSE PALPEBRAL PN- CORREÇÃO DE PTOSE PALPEBRAL (SIGTAP)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0408', 'TRATAMENTO MICROCIRÚRGICO DAS NEUROPATIAS COMPRESSIVAS (TUMORAL, INFLAMATÓRIO, ETC)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0409', 'TRATAMENTO MICROCIRÚRGICO DAS NEUROPATIAS COMPRESSIVAS (TUMORAL, INFLAMATÓRIO, ETC.+ TENOPLASTIA / ENXERTO DE TENDÃO - TRATAMENTO CIRÚRGICO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0410', 'TUMOR ANORRETAL - RESSECÇÃO ANORRETAL, TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0411', 'TUMOR VESICAL - RESSECÇÃO ENDOSCÓPICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0412', 'TUMOR ÓSSEO (RESSECÇÃO SIMPLES)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0413', 'TÚNEL DO CARPO - DESCOMPRESSÃO - PROCEDIMENTO VIDEOARTROSCÓPICO DE PUNHO E TÚNEL D', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0414', 'URETEROLITOTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0415', 'URETERORRENOLITOTRIPSIA FLEXÍVEL A LASER UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0416', 'URETERORRENOLITOTRIPSIA FLEXÍVEL UNILATERAL + COLOCAÇÃO URETEROSCÓPICA DE DUPLO J UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0417', 'URETERORRENOLITOTRIPSIA RÍGIDA UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0418', 'URETERORRENOLITOTRIPSIA RÍGIDA UNILATERAL A LASER + COLOCAÇÃO URETEROSCÓPICA DE DUPLO J -', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0419', 'URETROTOMIA INTERNA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0420', 'VARIZES - TRATAMENTO CIRÚRGICO DE DOIS MEMBROS', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0421', 'VARIZES - TRATAMENTO CIRÚRGICO DE UM MEMBRO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0422', 'VITRECTOMIA ANTERIOR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0423', 'VITRECTOMIA ANTERIOR - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0424', 'VITRECTOMIA ANTERIOR - PN (COMPLEMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0425', 'VITRECTOMIA ANTERIOR - PN (SIGTAP)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0426', 'VITRECTOMIA POSTERIOR COM INFUSÃO DE PERFLUOROCARBONO E ENDOLASER', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0427', 'VITRECTOMIA POSTERIOR COM INFUSÃO DE PERFLUOROCARBONO E ÓLEO DE SILICONE E ENDOLASER', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0428', 'VITRECTOMIA POSTERIOR E ÓLEO DE SILICONE E ENDOLASER - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0429', 'VITRECTOMIA POSTERIOR E ÓLEO DE SILICONE E ENDOLASER - PN (COMPLEMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0430', 'VITRECTOMIA POSTERIOR E ÓLEO DE SILICONE E ENDOLASER - PN (SIGTAP)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0431', 'VÍDEO LARINGOSCOPIA C/ ÓTICA RÍGIDA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0432', 'VÍDEO NASO LARINGOSCOPIA C/ ÓTICA FLEXÍVEL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0);

SELECT count(*) AS total_procedimentos_cadastrados FROM public.consultas_procedimentos;
