-- ====================================================================
-- MIGRATION: ATUALIZAÇÃO COMPLETA DA LISTA OFICIAL DE PROCEDIMENTOS DO SISTEMA
-- Zera a lista atual e insere os procedimentos por categoria: Consulta, Exame, Cirurgia
-- ====================================================================

-- 1. Garantir permissões de acesso
DROP POLICY IF EXISTS "Enable all access for consultas_procedimentos" ON public.consultas_procedimentos;
DROP POLICY IF EXISTS "Enable insert for all users" ON public.consultas_procedimentos;

CREATE POLICY "Enable all access for consultas_procedimentos" ON public.consultas_procedimentos
  FOR ALL USING (true) WITH CHECK (true);

-- 2. Zerar registros existentes (CASCADE para evitar erro de chaves estrangeiras)
TRUNCATE TABLE public.consultas_procedimentos CASCADE;

-- 3. Inserir a nova lista oficial de procedimentos
INSERT INTO public.consultas_procedimentos (code, name, type, status, recurso, total_quantity, available_quantity)
VALUES
-- ====================================================================
-- CATEGORIA: CONSULTA
-- ====================================================================
('0001', 'ACOMPANHAMENTO E AVALIACAO DE GLAUCOMA POR FUNDOSCOPIA E TONOMETRIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0002', 'CONSULTA CARDIOPEDIÁTRICA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0003', 'CONSULTA EM CABEÇA E PESCOÇO', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0004', 'CONSULTA EM CARDIOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0005', 'CONSULTA EM CIRURGIA GERAL', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0006', 'CONSULTA EM DERMATOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0007', 'CONSULTA EM ENDOCRINOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0008', 'CONSULTA EM GASTROENTEROLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0009', 'CONSULTA EM GASTROENTEROLOGIA (CONSULTÓRIO)', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0010', 'CONSULTA EM HEMATOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0011', 'CONSULTA EM MASTOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0012', 'CONSULTA EM NEFROLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0013', 'CONSULTA EM NEUROCIRURGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0014', 'CONSULTA EM NEUROLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0015', 'CONSULTA EM NEUROLOGIA PARA AVALIAÇÃO DE TRATAMENTO COM TOXINA BOTULÍNICA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0016', 'CONSULTA EM NEUROLOGIA PEDIÁTRICA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0017', 'CONSULTA EM OFTALMOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0018', 'CONSULTA EM ORTOPEDIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0019', 'CONSULTA EM OTORRINOLARINGOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0020', 'CONSULTA EM PNEUMOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0021', 'CONSULTA EM PROCTOLOGIA TERC', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0022', 'CONSULTA EM PSIQUIATRIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0023', 'CONSULTA EM REUMATOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0024', 'CONSULTA EM UROLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0025', 'CONSULTA ESPECIALIZADA EM ANESTESIA GERAL', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0026', 'CONSULTA ESPECIALIZADA EM CIRURGIA DE MAMOPLASTIA REDUTORA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0027', 'CONSULTA ESPECIALIZADA EM CIRURGIA VASCULAR', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0028', 'CONSULTA ESPECIALIZADA EM NEUROLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0029', 'CONSULTA MÉDICA EM ATENÇÃO ESPECIALIZADA EM GINECOLOGIA E OBSTETRÍCIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0030', 'CONSULTA MÉDICA ESPECIALIZADA - MIGUILIM', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0031', 'CONSULTA OFTALMOLÓGICA ESPECIALIZADA EM CATARATA, RETINA, GLAUCOMA E PLÁSTICA OCULAR', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0032', 'CONSULTA OFTALMOLÓGICA ESPECIALIZADA EM CATARATA, RETINA, GLAUCOMA E PLÁSTICA OCULAR (PN)', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0033', 'CONSULTA P/ DIAGNOSTICO/ REAVALIACAO DE GLAUCOMA (01 ANO)', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0034', 'CONSULTA PRE CIRURGICA EM ANESTESIOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0035', 'CONSULTA PRE CIRURGICA EM CIRURGIA GERAL', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0036', 'CONSULTA PRE CIRURGICA EM CIRURGIA VASCULAR', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0037', 'CONSULTA PRE CIRURGICA EM COLOPROCTOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0038', 'CONSULTA PRE CIRURGICA EM GINECOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0039', 'CONSULTA PRE CIRURGICA EM MASTOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0040', 'CONSULTA PRE CIRURGICA EM ORTOPEDIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0041', 'CONSULTA PRE CIRURGICA EM OTORRINOLARINGOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0042', 'CONSULTA PRE CIRURGICA EM UROLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0043', 'CONSULTA PRE-CIRÚRGICA EM NEUROCIRURGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0044', 'CONSULTA RETORNO COM REALIZAÇÃO DE RAIO-X', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),

-- ====================================================================
-- CATEGORIA: EXAME
-- ====================================================================
('0045', 'ANATOMO - BIOPSIA EM PECA CIRURGICA SIMPLES OU PELE', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0046', 'ANATOMO COLORAÇÃO ESPECIAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0047', 'ANGIORESSONÂNCIA 1 SEGMENTO: COXA OU PERNA; BRAÇO OU ANTEBRAÇO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0048', 'ANGIORESSONÂNCIA 2 SEGMENTOS: COXA E PERNA; BRAÇO E ANTEBRAÇO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0049', 'ANGIORESSONÂNCIA ARTERIAL DO CRÂNIO COM 1 SEGMENTO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0050', 'ANGIORESSONÂNCIA ARTERIAL DO CRÂNIO COM 1 SEGMENTO (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0051', 'ANGIORESSONÂNCIA ARTERIAL DO CRÂNIO COM 1 SEGMENTO (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0052', 'ANGIORESSONÂNCIA ARTERIAL DO CRÂNIO COM 2 SEGMENTOS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0053', 'ANGIORESSONÂNCIA ARTERIAL DO PESCOÇO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0054', 'ANGIORESSONÂNCIA DA AORTA ABDOMINAL COM 1 SEGMENTO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0055', 'ANGIORESSONÂNCIA DA AORTA ABDOMINAL COM 2 SEGMENTOS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0056', 'ANGIORESSONÂNCIA DE AORTA TORÁCICA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0057', 'ANGIORESSONÂNCIA DO TÓRAX', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0058', 'ANGIORESSONÂNCIA SACRO ILÍACAS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0059', 'ANGIORESSONÂNCIA UNILATERAL ARTERIAL OU VENOSA DE MEMBRO INFERIOR (1 SEGMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0060', 'ANGIORESSONÂNCIA UNILATERAL ARTERIAL OU VENOSA DE MEMBRO SUPERIOR (1 SEGMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0061', 'ANGIORESSONÂNCIA VENOSA DO CRÂNIO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0062', 'ANGIORESSONÂNCIA VENOSA DO CRÂNIO (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0063', 'ANGIORESSONÂNCIA VENOSA DO CRÂNIO (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0064', 'ANGIORESSONÂNCIA VENOSA DO PESCOÇO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0065', 'ANGIOTOMOGRAFIA ARTERIAL DA PELVE', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0066', 'ANGIOTOMOGRAFIA ARTERIAL DE ABDOMEN SUPERIOR', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0067', 'ANGIOTOMOGRAFIA ARTERIAL DE PESCOÇO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0068', 'ANGIOTOMOGRAFIA ARTERIAL DO CRÂNIO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0069', 'ANGIOTOMOGRAFIA ARTERIAL DO TÓRAX', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0070', 'ANGIOTOMOGRAFIA DA BASE DO CRÂNIO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0071', 'ANGIOTOMOGRAFIA DA PORTA-ESPLÊNICA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0072', 'ANGIOTOMOGRAFIA DE ABDOMEN ( AORTA ABDOMINAL)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0073', 'ANGIOTOMOGRAFIA DE AORTA ABDOMINAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0074', 'ANGIOTOMOGRAFIA DE AORTA TORÁCICA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0075', 'ANGIOTOMOGRAFIA DE AORTA TÓRACO-ABDOMINAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0076', 'ANGIOTOMOGRAFIA DE ARTÉRIAS MESENTÉRICAS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0077', 'ANGIOTOMOGRAFIA DE ARTÉRIAS RENAIS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0078', 'ANGIOTOMOGRAFIA DE CARÓTIDAS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0079', 'ANGIOTOMOGRAFIA DE CORONÁRIAS COM CONTRASTE', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0080', 'ANGIOTOMOGRAFIA DE MEMBROS INFERIORES', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0081', 'ANGIOTOMOGRAFIA DE SEGMENTO APENDICULAR (COXA OU PERNA)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0082', 'ANGIOTOMOGRAFIA DO TÓRAX (TEP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0083', 'ANGIOTOMOGRAFIA DOS MEMBROS SUPERIORES', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0084', 'ANGIOTOMOGRAFIA DOS VASOS INTRAC. DA BASE', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0085', 'ANGIOTOMOGRAFIA VENOSA DA PELVE', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0086', 'ANGIOTOMOGRAFIA VENOSA DE ABDOMEN SUPERIOR', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0087', 'ANGIOTOMOGRAFIA VENOSA DO CRÂNIO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0088', 'ANGIOTOMOGRAFIA VENOSA DO PESCOÇO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0089', 'ANGIOTOMOGRAFIA VENOSA DO TÓRAX', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0090', 'ANUSCOPIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0091', 'ARTRO RESSONÂNCIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0092', 'AUDIOMETRIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0093', 'AVALIAÇÃO URODINÂMICA COMPLETA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0094', 'BIOMETRIA ULTRASSÔNICA MONOCULAR', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0095', 'BIOMICROSCOPIA DE FUNDO DE OLHO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0096', 'BIOPSIA EM LAMINAS DE PAAF ATÉ 5 EXAMES', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0097', 'CAMPIMETRIA COMPUTADORIZADA - CAMPO VISUAL (CVC) - PN', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0098', 'CAMPIMETRIA COMPUTADORIZADA COM EMISSÃO DE LAUDO - CISAMAPI', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0099', 'CATETERISMO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0100', 'CERATOMETRIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0101', 'COLONOSCOPIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0102', 'COLONOSCOPIA (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0103', 'COLONOSCOPIA (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0104', 'COLONOSCOPIA COM MUCOSECTOMIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0105', 'COLONOSCOPIA COM MUCOSECTOMIA E HESMOSTASIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0106', 'COLONOSCOPIA COM POLPECTOMIA COM PÓLIPO PEDICULADO DE GRANDE DIMENSÃO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0107', 'COLORACAO ESPECIAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0108', 'CURVA DIÁRIA DE PRESSÃO OCULAR - CDPO (MÍNIMO DE 3 MEDIDAS)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0109', 'DENSITOMETRIA OSSEA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0110', 'DUPPLEX SCAN 1 MEMBRO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0111', 'DUPPLEX SCAN 2 MEMBROS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0112', 'DUPPLEX SCAN DE ARTÉRIAS CERVICAIS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0113', 'DUPPLEX SCAN DE ARTÉRIAS ILÍACAS BILATERAIS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0114', 'DUPPLEX SCAN DE ARTÉRIAS RENAIS (REAJUSTADO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0115', 'DUPPLEX SCAN DE CARÓTIDAS E VERTEBRAIS (REAJUSTADO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0116', 'DUPPLEX SCAN DE VIAS SUBCLÁVICAS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0117', 'ECOCARDIOGRAFIA BI-DIMENSIONAL COM OU SEM DOPLLER', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0118', 'ECOCARDIOGRAFIA COM OU SEM DOPLLER (REAJUSTADO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0119', 'ECOCARDIOGRAMA FETAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0120', 'ECOCARDIOGRAMA TRANSESOFAGICO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0121', 'ELETROENCEFALOGRAMA (LAUDO À DISTÂNCIA)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0122', 'ELETRONEUROMIOGRAMA (1 OU 2 MEMBROS) (REAJUSTADO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0123', 'EMISSÕES OTOACUSTICAS EVOCADAS P/ TRIAGEM AUDITIVA (TESTE DA ORELHINHA)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0124', 'ENDOSCOPIA DIGESTIVA ALTA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0125', 'ENDOSCOPIA DIGESTIVA ALTA (ABRE CAMPO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0126', 'ENDOSCOPIA DIGESTIVA ALTA (CISAMAPI PONTE NOVA)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0127', 'ENTEROTOMOGRAFIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0128', 'ESCANOMETRIA DE MEMBROS INFERIORES', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0129', 'ESPIROMETRIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0130', 'ESTUDO DE EMISSÕES OTOACUSTICAS EVOCADAS TRANSITÓRIAS E PRODUTOS DE DISTORÇÃO (EOA)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0131', 'GONIOSCOPIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0132', 'IMPEDANCIOMETRIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0133', 'LOGOAUDIOMETRIA (LDV- IRF -LRF)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0134', 'MAMOGRAFIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0135', 'MICROSCOPIA ESPECULAR DE CÓRNEA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0136', 'MICROSCOPIA ESPECULAR DE CORNEA - PN', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0137', 'MONITORAMENTO PELO SISTEMA HOLTER 24 HS (3 CANAIS)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0138', 'MONITORIZAÇÃO AMBULATORIAL DE PRESSÃO ARTERIAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0139', 'PAQUIMETRIA ULTRASSÔNICA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0140', 'PENTACAM BINOCULAR', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0141', 'POLISSONOGRAFIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0142', 'POLISSONOGRAFIA (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0143', 'POLISSONOGRAFIA (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0144', 'POLISSONOGRAFIA DO SONO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0145', 'RADIOGRAFIA BILATERAL DE ORBITAS (PA / OBLIQUAS / HIRTZ)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0146', 'RADIOGRAFIA CLAVICULAR', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0147', 'RADIOGRAFIA DA MÃO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0148', 'RADIOGRAFIA DE ABDMEN AGUDO (MINIMO DE 3 INCIDENCIAS)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0149', 'RADIOGRAFIA DE ABDOMEN (AP / LATERAL / LOCALIZADA )', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0150', 'RADIOGRAFIA DE ABDOMEN SIMPLES (AP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0151', 'RADIOGRAFIA DE ANTEBRAÇO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0152', 'RADIOGRAFIA DE ARTICULAÇÃO ACROMIO-CLAVICULAR', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0153', 'RADIOGRAFIA DE ARTICULAÇÃO COXO-FEMORAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0154', 'RADIOGRAFIA DE ARTICULAÇÃO ESCAPULO-UMERAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0155', 'RADIOGRAFIA DE ARTICULAÇÃO ESTERNO-CLAVICULAR', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0156', 'RADIOGRAFIA DE ARTICULAÇÃO SACRO-ILÍACA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0157', 'RADIOGRAFIA DE ARTICULACAO TEMPORO-MANDIBULAR BILATERAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0158', 'RADIOGRAFIA DE ARTICULAÇÃO TIBIO-TARSICA (TORNOZELO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0159', 'RADIOGRAFIA DE BACIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0160', 'RADIOGRAFIA DE BRAÇO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0161', 'RADIOGRAFIA DE CALCANEO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0162', 'RADIOGRAFIA DE CAVUM (LATERAL/ HIRTZ)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0163', 'RADIOGRAFIA DE COLUNA CERVICAL (AP / LATERAL / TO / OBLIQUAS)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0164', 'RADIOGRAFIA DE COLUNA LOMBO-SACRA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0165', 'RADIOGRAFIA DE COLUNA LOMBO-SACRA (C/ OBLIQUAS)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0166', 'RADIOGRAFIA DE COLUNA TORACICA (AP / LATERAL) (DORSAL)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0167', 'RADIOGRAFIA DE COLUNA TÓRACO-LOMBAR', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0168', 'RADIOGRAFIA DE COSTELAS (POR HEMITORAX)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0169', 'RADIOGRAFIA DE COTOVELO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0170', 'RADIOGRAFIA DE COXA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0171', 'RADIOGRAFIA DE CRANIO (PA / LATERAL / OBLIQUA/ BRETTON / HIRTZ)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0172', 'RADIOGRAFIA DE CRANIO (PA /LATERAL)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0173', 'RADIOGRAFIA DE DEDOS DA MÃO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0174', 'RADIOGRAFIA DE ESTRENO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0175', 'RADIOGRAFIA DE JOELHO (AP / LATERAL)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0176', 'RADIOGRAFIA DE JOELHO OU PATELA (AP / LATERAL / AXIAL)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0177', 'RADIOGRAFIA DE JOELHO OU PATELA (AP / LATERAL / OBLIQUA / 3 AXIAIS )', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0178', 'RADIOGRAFIA DE MÃO E DE PUNHO ( P/ DETERMINAÇÃO DE IDADE OSSEA)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0179', 'RADIOGRAFIA DE MASTOIDE/ROCHEDOS (BILATERAL)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0180', 'RADIOGRAFIA DE MAXILAR (PA / OBLIQUA)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0181', 'RADIOGRAFIA DE OMOPLATA/ OMBRO (TRÊS POSIÇÕES)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0182', 'RADIOGRAFIA DE OSSOS DA FACE (MN / LATERAL / HIRTZ )', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0183', 'RADIOGRAFIA DE PÉ / DEDOS DO PÉ', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0184', 'RADIOGRAFIA DE PERNA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0185', 'RADIOGRAFIA DE PUNHO (AP / LATERAL /OBLIQUAS)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0186', 'RADIOGRAFIA DE REGIÃO SACRO-COCCIGEA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0187', 'RADIOGRAFIA DE SEIOS DA FACE (FN / MN / LATERAL / HIRTZ)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0188', 'RADIOGRAFIA DE SELA TURSICA (PA / LATERAL / BRETTON)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0189', 'RADIOGRAFIA DE TORAX (APICO-LORDORTICA)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0190', 'RADIOGRAFIA DE TORAX (PA / LATERAL / OBLIQUA)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0191', 'RADIOGRAFIA DE TORAX (PA E PERFIL)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0192', 'RADIOGRAFIA DE TORAX (PA)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0193', 'RADIOGRAFIA PANORAMICA DE MANDIBULA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0194', 'RADIOGRAFIA PANORAMICA DE MEMBROS INFERIORES', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0195', 'RADIOGRAFIA SACRO ILÍACA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0196', 'RAIO-X TERCERIZADO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0197', 'RESSONÂNCIA DO CORAÇÃO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0198', 'RESSONÂNCIA MAGNÉTICA ANGIOGRAFIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0199', 'RESSONÂNCIA MAGNÉTICA AORTA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0200', 'RESSONÂNCIA MAGNÉTICA ATM', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0201', 'RESSONÂNCIA MAGNÉTICA ATM (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0202', 'RESSONÂNCIA MAGNÉTICA ATM (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0203', 'RESSONÂNCIA MAGNÉTICA COXO-FEMURAL BILATERAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0204', 'RESSONÂNCIA MAGNÉTICA DA BACIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0205', 'RESSONÂNCIA MAGNÉTICA DA BASE DO CRÂNIO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0206', 'RESSONÂNCIA MAGNÉTICA DA BOLSA ESCROTAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0207', 'RESSONÂNCIA MAGNÉTICA DA COLANGIOGRAFIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0208', 'RESSONÂNCIA MAGNÉTICA DA COLUNA CERVICAL OU DORSAL OU LOMBAR', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0209', 'RESSONÂNCIA MAGNÉTICA DA COLUNA CERVICAL OU DORSAL OU LOMBAR (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0210', 'RESSONÂNCIA MAGNÉTICA DA COLUNA CERVICAL OU DORSAL OU LOMBAR (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0211', 'RESSONÂNCIA MAGNÉTICA DA COLUNA TORÁCICA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0212', 'RESSONÂNCIA MAGNÉTICA DA COLUNA TORÁCICA (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0213', 'RESSONÂNCIA MAGNÉTICA DA COLUNA TORÁCICA (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0214', 'RESSONÂNCIA MAGNÉTICA DA COXA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0215', 'RESSONÂNCIA MAGNÉTICA DA FACE', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0216', 'RESSONÂNCIA MAGNÉTICA DA MAMA BILATERAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0217', 'RESSONÂNCIA MAGNÉTICA DA MÃO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0218', 'RESSONÂNCIA MAGNÉTICA DA MÃO (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0219', 'RESSONÂNCIA MAGNÉTICA DA MÃO (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0220', 'RESSONÂNCIA MAGNÉTICA DA PELVE (NÃO INCLUI ARTICULAÇÕES COXOFEMORAIS)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0221', 'RESSONÂNCIA MAGNÉTICA DA PELVE (NÃO INCLUI ARTICULAÇÕES COXOFEMORAIS) (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0222', 'RESSONÂNCIA MAGNÉTICA DA PELVE (NÃO INCLUI ARTICULAÇÕES COXOFEMORAIS) (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0223', 'RESSONÂNCIA MAGNÉTICA DA PERNA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0224', 'RESSONÂNCIA MAGNÉTICA DAS MASTÓIDES', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0225', 'RESSONÂNCIA MAGNÉTICA DAS ÓRBITAS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0226', 'RESSONÂNCIA MAGNÉTICA DO ABDOMEN SUPERIOR', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0227', 'RESSONÂNCIA MAGNÉTICA DO ABDOMEN SUPERIOR (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0228', 'RESSONÂNCIA MAGNÉTICA DO ABDOMEN SUPERIOR (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0229', 'RESSONÂNCIA MAGNÉTICA DO ABDOMEN TOTAL (ABDOMEN SUPERIOR +PELVE)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0230', 'RESSONÂNCIA MAGNÉTICA DO ABDOMEN TOTAL (ABDOMEN SUPERIOR +PELVE) (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0231', 'RESSONÂNCIA MAGNÉTICA DO ABDOMEN TOTAL (ABDOMEN SUPERIOR +PELVE) (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0232', 'RESSONÂNCIA MAGNÉTICA DO ANTEBRAÇO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0233', 'RESSONÂNCIA MAGNÉTICA DO ANTEPÉ', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0234', 'RESSONÂNCIA MAGNÉTICA DO BRAÇO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0235', 'RESSONÂNCIA MAGNÉTICA DO COTOVELO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0236', 'RESSONÂNCIA MAGNÉTICA DO COXO-FEMURAL UNILATERAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0237', 'RESSONÂNCIA MAGNÉTICA DO CRÂNIO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0238', 'RESSONÂNCIA MAGNÉTICA DO CRÂNIO (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0239', 'RESSONÂNCIA MAGNÉTICA DO DEDO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0240', 'RESSONÂNCIA MAGNÉTICA DO JOELHO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0241', 'RESSONÂNCIA MAGNÉTICA DO JOELHO (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0242', 'RESSONÂNCIA MAGNÉTICA DO JOELHO (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0243', 'RESSONÂNCIA MAGNÉTICA DO MEMBRO SUPERIOR UNILATERAL (NÃO INCLUI MÃO E ARTICULAÇÕES)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0244', 'RESSONÂNCIA MAGNÉTICA DO OMBRO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0245', 'RESSONÂNCIA MAGNÉTICA DO OMBRO (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0246', 'RESSONÂNCIA MAGNÉTICA DO OMBRO (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0247', 'RESSONÂNCIA MAGNÉTICA DO PÉ', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0248', 'RESSONÂNCIA MAGNÉTICA DO PÉ (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0249', 'RESSONÂNCIA MAGNÉTICA DO PÉ (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0250', 'RESSONÂNCIA MAGNÉTICA DO PESCOÇO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0251', 'RESSONÂNCIA MAGNÉTICA DO PESCOÇO (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0252', 'RESSONÂNCIA MAGNÉTICA DO PESCOÇO (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0253', 'RESSONÂNCIA MAGNÉTICA DO PLEXO BRAQUIAL UNILATERAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0254', 'RESSONÂNCIA MAGNÉTICA DO PUNHO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0255', 'RESSONÂNCIA MAGNÉTICA DO PUNHO (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0256', 'RESSONÂNCIA MAGNÉTICA DO PUNHO (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0257', 'RESSONÂNCIA MAGNÉTICA DO QUADRIL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0258', 'RESSONÂNCIA MAGNÉTICA DO QUADRIL (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0259', 'RESSONÂNCIA MAGNÉTICA DO QUADRIL (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0260', 'RESSONÂNCIA MAGNÉTICA DO SACRO COCCIX', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0261', 'RESSONÂNCIA MAGNÉTICA DO SACRO ILÍACO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0262', 'RESSONÂNCIA MAGNÉTICA DO TÓRAX', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0263', 'RESSONÂNCIA MAGNÉTICA DOS OSSOS TEMPORAIS BILATERAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0264', 'RESSONÂNCIA MAGNÉTICA DOS SEIOS DA FACE', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0265', 'RESSONÂNCIA MAGNÉTICA FETAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0266', 'RESSONÂNCIA MAGNÉTICA HIPÓFISE DA SELA TÚRCICA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0267', 'RESSONÂNCIA MAGNÉTICA HIPÓFISE DA SELA TÚRCICA (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0268', 'RESSONÂNCIA MAGNÉTICA HIPÓFISE DA SELA TÚRCICA (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0269', 'RESSONÂNCIA MAGNÉTICA URORRESSONÂNCIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0270', 'RETINOGRAFIA BINOCULAR (GLAUCOMA)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0271', 'RETINOGRAFIA BINOCULAR (GLAUCOMA) (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0272', 'RETINOGRAFIA BINOCULAR (GLAUCOMA) (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0273', 'RETINOGRAFIA COLORIDA BINOCULAR', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0274', 'RETINOGRAFIA COLORIDA BINOCULAR - PN', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0275', 'RETINOGRAFIA FLUORESCENTE BINOCULAR (ANGIOFLUORECÊNCIA)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0276', 'RETINOGRAFIA FLUORESCENTE BINOCULAR (ANGIOFLUORECÊNCIA) - PN', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0277', 'RETINOGRAFIA FLUORESCENTE BINOCULAR (ANGIOFLUORECÊNCIA) - PN (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0278', 'RETINOGRAFIA FLUORESCENTE BINOCULAR (ANGIOFLUORECÊNCIA) - PN (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0279', 'RX PANORÂMICO MEMBROS COLUNA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0280', 'RX PANORÂMICO MEMBROS INFERIORES', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0281', 'RX PANORÂMICO MEMBROS SUPERIORES', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0282', 'TAP TEST - AVALIAÇÃO DE POSSÍVEL RESPOSTA DE TRATAMENTO CIRÚRGICO PARA HIDROCEFALIA DE PRESSÃO NORMAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0283', 'TESTE DE ESFORÇO/ TESTE ERGOMÉTRICO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0284', 'TESTE DE ESFORÇO/TESTE ERGOMÉTRICO (REAJUSTADO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0285', 'TESTE DE SCHIRMER', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0286', 'TESTE DE SCHIRMER - PN', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0287', 'TESTE DE SOBRECARGA HÍDRICA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0288', 'TESTE ERGOMETRICO TERCEIRIZADO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0289', 'TESTE ERGOMETRICO TERCEIRIZADO (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0290', 'TESTE ERGOMETRICO TERCEIRIZADO (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0291', 'TOMOGRAFIA COMPUTADORIZADA DA ARTICULAÇÃO - SEGMENTO APENDICULAR (PUNHO, OMBRO, MÃO, PÉ, ETC)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0292', 'TOMOGRAFIA COMPUTADORIZADA DA ARTICULAÇÃO - SEGMENTO APENDICULAR (PUNHO, OMBRO, MÃO, PÉ, ETC) - SUS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0293', 'TOMOGRAFIA COMPUTADORIZADA DA ARTICULAÇÃO - SEGMENTO APENDICULAR (PUNHO, OMBRO, MÃO, PÉ, ETC) (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0294', 'TOMOGRAFIA COMPUTADORIZADA DA ARTICULAÇÃO - SEGMENTO APENDICULAR (PUNHO, OMBRO, MÃO, PÉ, ETC) (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0295', 'TOMOGRAFIA COMPUTADORIZADA DA ARTICULAÇÃO (ESTERNO CLAVICULAR OU OMBRO OU COTOVELO OU PUNHO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0296', 'TOMOGRAFIA COMPUTADORIZADA DA ARTICULAÇÃO (ESTERNO CLAVICULAR OU OMBRO OU COTOVELO OU PUNHO) (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0297', 'TOMOGRAFIA COMPUTADORIZADA DA ARTICULAÇÃO (ESTERNO CLAVICULAR OU OMBRO OU COTOVELO OU PUNHO) (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0298', 'TOMOGRAFIA COMPUTADORIZADA DA ARTICULAÇÃO TEMPORO-MANDIBULAR UNILATERAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0299', 'TOMOGRAFIA COMPUTADORIZADA DA COLUNA - CADA SEGMENTO ADICIONAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0300', 'TOMOGRAFIA COMPUTADORIZADA DA COLUNA CERVICAL OU DORSAL OU LOMBO-SACRA (ATÉ 3 SEGMENTOS)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0301', 'TOMOGRAFIA COMPUTADORIZADA DA COLUNA CERVICAL OU DORSAL OU LOMBO-SACRA (ATÉ 3 SEGMENTOS) (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0302', 'TOMOGRAFIA COMPUTADORIZADA DA COLUNA CERVICAL OU DORSAL OU LOMBO-SACRA (ATÉ 3 SEGMENTOS) (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0303', 'TOMOGRAFIA COMPUTADORIZADA DA COXA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0304', 'TOMOGRAFIA COMPUTADORIZADA DA COXA- SUS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0305', 'TOMOGRAFIA COMPUTADORIZADA DA FACE / SEIOS DA FACE / ARTICULAÇÕES TEMPORO-MANDIBULARES', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0306', 'TOMOGRAFIA COMPUTADORIZADA DA FACE / SEIOS DA FACE / ARTICULAÇÕES TEMPORO-MANDIBULARES (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0307', 'TOMOGRAFIA COMPUTADORIZADA DA FACE / SEIOS DA FACE / ARTICULAÇÕES TEMPORO-MANDIBULARES (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0308', 'TOMOGRAFIA COMPUTADORIZADA DA FACE/SEIOS DA FACE/ARTICULAÇÕES TEMPORO-MANDIBULARES - SUS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0309', 'TOMOGRAFIA COMPUTADORIZADA DA PELVE OU BACIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0310', 'TOMOGRAFIA COMPUTADORIZADA DA PELVE OU BACIA - SUS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0311', 'TOMOGRAFIA COMPUTADORIZADA DA REGIÃO CERVICAL (TIREÓIDE, PARATIRÓIDE, FARINGE E ESTRUTURAS)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0312', 'TOMOGRAFIA COMPUTADORIZADA DA SELA TÚRCICA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0313', 'TOMOGRAFIA COMPUTADORIZADA DA SELA TÚRCICA - SUS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0314', 'TOMOGRAFIA COMPUTADORIZADA DA SELA TÚRCICA (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0315', 'TOMOGRAFIA COMPUTADORIZADA DA SELA TÚRCICA (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0316', 'TOMOGRAFIA COMPUTADORIZADA DA TRANSIÇÃO CRÂNIO CERVICAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0317', 'TOMOGRAFIA COMPUTADORIZADA DAS ADRENAIS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0318', 'TOMOGRAFIA COMPUTADORIZADA DAS ART. MEMBROS INFERIORES', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0319', 'TOMOGRAFIA COMPUTADORIZADA DAS ART. MEMBROS SUPERIORES (OMBRO, COTOVELO, PUNHO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0320', 'TOMOGRAFIA COMPUTADORIZADA DAS ARTICULAÇÕES SACRO ILÍACAS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0321', 'TOMOGRAFIA COMPUTADORIZADA DAS MASTÓIDES OU ORELHAS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0322', 'TOMOGRAFIA COMPUTADORIZADA DAS ÓRBITAS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0323', 'TOMOGRAFIA COMPUTADORIZADA DE COERÊNCIA ÓPTICA - OCT', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0324', 'TOMOGRAFIA COMPUTADORIZADA DE COERÊNCIA ÓPTICA - OCT (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0325', 'TOMOGRAFIA COMPUTADORIZADA DE COERÊNCIA ÓPTICA - OCT (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0326', 'TOMOGRAFIA COMPUTADORIZADA DE COERÊNCIA ÓPTICA SPECTRALLIS - BINOCULAR', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0327', 'TOMOGRAFIA COMPUTADORIZADA DE COLUNA LOMBO-SACRA C/ OU S/ CONTRASTE - SUS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0328', 'TOMOGRAFIA COMPUTADORIZADA DO ABDOMEN SUPERIOR', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0329', 'TOMOGRAFIA COMPUTADORIZADA DO ABDOMEN SUPERIOR - SUS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0330', 'TOMOGRAFIA COMPUTADORIZADA DO ABDOMEN SUPERIOR (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0331', 'TOMOGRAFIA COMPUTADORIZADA DO ABDOMEN SUPERIOR (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0332', 'TOMOGRAFIA COMPUTADORIZADA DO ABDOMEN TOTAL (ABDOMEN SUPERIOR, PELVE E RETROPERITÔNIO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0333', 'TOMOGRAFIA COMPUTADORIZADA DO CRÂNIO C/ CONTRASTE OU S/ CONTRASTE', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0334', 'TOMOGRAFIA COMPUTADORIZADA DO CRÂNIO C/ CONTRASTE OU S/ CONTRASTE (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0335', 'TOMOGRAFIA COMPUTADORIZADA DO CRÂNIO C/ CONTRASTE OU S/ CONTRASTE (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0336', 'TOMOGRAFIA COMPUTADORIZADA DO CRANIO C/CONTRASTE OU S/ CONTRASTE - SUS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0337', 'TOMOGRAFIA COMPUTADORIZADA DO HEMITÓRAX/ MEDIASTINO (POR PLANO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0338', 'TOMOGRAFIA COMPUTADORIZADA DO JOELHO (PROTOCOLO DE LYON)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0339', 'TOMOGRAFIA COMPUTADORIZADA DO PESCOÇO (PARTES MOLES, LARINGE, TIREÓIDE, FARINGE E GLÂNDULAS SALIVARES)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0340', 'TOMOGRAFIA COMPUTADORIZADA DO PESCOÇO (PARTES MOLES, LARINGE, TIREÓIDE, FARINGE E GLÂNDULAS SALIVARES) (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0341', 'TOMOGRAFIA COMPUTADORIZADA DO PESCOÇO (PARTES MOLES, LARINGE, TIREÓIDE, FARINGE E GLÂNDULAS SALIVARES) (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0342', 'TOMOGRAFIA COMPUTADORIZADA DO PESCOÇO (PARTES MOLES, LARINGE, TIREÓIDE, FARINGE E GLÂNDULAS SALIVARES) -SUS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0343', 'TOMOGRAFIA COMPUTADORIZADA DO QUADRIL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0344', 'TOMOGRAFIA COMPUTADORIZADA DO SEGMENTO APENDICULAR (BRAÇO OU ANTEBRAÇO OU MÃO OU COXA OU PERNA OU PÉ)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0345', 'TOMOGRAFIA COMPUTADORIZADA DO SEGMENTO APENDICULAR (PERNA OU TORNOZELO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0346', 'TOMOGRAFIA COMPUTADORIZADA DO SEGMENTO APENDICULAR (PERNA OU TORNOZELO) (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0347', 'TOMOGRAFIA COMPUTADORIZADA DO SEGMENTO APENDICULAR (PERNA OU TORNOZELO) (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0348', 'TOMOGRAFIA COMPUTADORIZADA DO TÓRAX', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0349', 'TOMOGRAFIA COMPUTADORIZADA DO TÓRAX - SUS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0350', 'TOMOGRAFIA COMPUTADORIZADA DO TÓRAX (COMPLEMENTO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0351', 'TOMOGRAFIA COMPUTADORIZADA DO TÓRAX (SIGTAP)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0352', 'TOMOGRAFIA COMPUTADORIZADA DOS SEGMENTOS APENDICULARES (BRAÇO, ANTEBRAÇO, MAO, COXA, PERNA OU PÉ - SUS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0353', 'TONOMETRIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0354', 'TOPOGRAFIA COMPUTADORIZADA DA CÓRNEA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0355', 'TOPOGRAFIA COMPUTADORIZADA DA CÓRNEA - PN', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0356', 'ULTRASOM OBSTÉTRICA COM DOPPLER COLORIDO TERC.', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0357', 'ULTRASOM PÉLVICA (GINECOLÓGICA) TERC.', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0358', 'ULTRASOM TRANSVAGINAL TERC.', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0359', 'ULTRA-SONOGRAFIA ABDOMINAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0360', 'ULTRA-SONOGRAFIA COM DOPPLER', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0361', 'ULTRA-SONOGRAFIA DE ABDOMEN SUPERIOR (FÍGADO, VESÍCULA, VIAS BILIARES)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0362', 'ULTRA-SONOGRAFIA DE ABDOMEN TOTAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0363', 'ULTRA-SONOGRAFIA DE APARELHO URINÁRIO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0364', 'ULTRA-SONOGRAFIA DE BOLSA ESCROTAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0365', 'ULTRA-SONOGRAFIA DE GLOBO OCULAR/ ÓRBITA (MONOCULAR) ECO B', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0366', 'ULTRA-SONOGRAFIA DE PARTES MOLES', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0367', 'ULTRA-SONOGRAFIA DE PRÓSTATA (VIA ABDOMINAL)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0368', 'ULTRA-SONOGRAFIA DE TIREÓIDE', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0369', 'ULTRA-SONOGRAFIA DO HIPOCÔNDRIO DIREITO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0370', 'ULTRA-SONOGRAFIA MAMARIA BILATERAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0371', 'ULTRA-SONOGRAFIA MORFOLÓGICA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0372', 'ULTRA-SONOGRAFIA OBSTÉTRICA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0373', 'ULTRA-SONOGRAFIA OBSTÉTRICA COM DOPPLER COLORIDO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0374', 'ULTRA-SONOGRAFIA PÉLVICA (GINECOLÓGICA)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0375', 'ULTRA-SONOGRAFIA TRANSVAGINAL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0376', 'ULTRASSOM ABDOMEN SUPERIOR TERC', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0377', 'ULTRASSOM ABDOMINAL TERC.', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0378', 'ULTRASSOM COM DOPPLER TERC.', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0379', 'ULTRASSOM DE ABDOMEN TOTAL TERC.', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0380', 'ULTRASSOM DE APARELHO URINÁRIO TERC.', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0381', 'ULTRASSOM DE ARTICULAÇÃO TERC.', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0382', 'ULTRASSOM DE BOLSA ESCROTAL TERC.', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0383', 'ULTRASSOM DE PARTES MOLES TERC.', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0384', 'ULTRASSOM DE PRÓSTATA (VIA ABDOMINAL) TERC.', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0385', 'ULTRASSOM DE TIREÓIDE TERC.', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0386', 'ULTRASSOM DO HIPOCÔNDRIO DIREITO TERC.', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0387', 'ULTRASSOM MAMARIA BILATERAL TERC.', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0388', 'ULTRASSOM OBSTÉTRICA TERC', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0389', 'ULTRASSONOGRAFIA DA PROSTATA COM BIOPSIA (SEM SEDAÇÃO)', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0390', 'ULTRASSONOGRAFIA DA PRÓSTATA COM BIOPSIA COM SEDAÇÃO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0391', 'ULTRASSONOGRAFIA DE ABDOMEM TOTAL COM DOPPLER', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0392', 'ULTRASSONOGRAFIA DE ARTICULAÇÃO COM DOPPLER', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0393', 'ULTRASSONOGRAFIA MORFOLÓGICA COM DOPPLER', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0394', 'UROTOMOGRAFIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0395', 'VÍDEO LARINGOSCOPIA C/ ÓTICA RÍGIDA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0396', 'VÍDEO NASO LARINGOSCOPIA C/ ÓTICA FLEXÍVEL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),

-- ====================================================================
-- CATEGORIA: CIRURGIA
-- ====================================================================
('0397', 'ABSCESSO ANORRETAL - DRENAGEM', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0398', 'ADENO-AMIGDALECTOMIA X 2 + CORNETO INFERIOR - CAUTERIZAÇÃO LINEAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0399', 'ADENO-AMIGDALECTOMIA X 2 + CORNETO INFERIOR - CAUTERIZAÇÃO LINEAR - UNILATERAL X2 +TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL X2', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0400', 'ADENOIDECTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0401', 'AMIGDALECTOMIA C/ ADENOIDECTOMIA (COM OU SEM TURBINOPLASTIA)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0402', 'ANESTESIA GERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0403', 'ANGIOPLASTIA CORONARIANA C/ IMPLANTE DE DOIS STENTS - 01 DIÁRIA ENF.', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0404', 'ANGIOPLASTIA CORONARIANA COM IMPLANTE DE STENT - 01 DIÁRIA ENF.', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0405', 'ANGIOPLASTIA CORONARIANA PRIMARIA-INCLUINDO 01 DIÁRIA ENF', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0406', 'ANGIOPLASTIA CORONARIANA SEM STENT - 01 DIÁRIA ENF.', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0407', 'APENDICECTOMIA POR VIDEOLAPAROSCOPIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0408', 'APLICAÇÃO DE TOXINA BOTULÍNICA (NEUROLOGIA) SEM O MEDICAMENTO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0409', 'APLICAÇÃO DE TOXINA BOTULÍNICA FACIAL - C/ PRODUTO - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0410', 'APLICAÇÃO DE TOXINA BOTULÍNICA FACIAL - INCLUINDO O PRODUTO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0411', 'ARTRODESE AO NÍVEL DO TORNOZELO - TRATAMENTO CIRÚRGICO + PÉ PLANO/ PÉ CAVO/ COALISÃO TARSAL - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0412', 'ARTRODESE DE PUNHO + ENXERTO ÓSSEO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0413', 'ARTROPLASTIA TOTAL DE JOELHO COM IMPLANTES - TRATAMENTO CIRÚRGICO PRÓTESE IMPORTADA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0414', 'ARTROPLASTIA TOTAL DE JOELHO COM IMPLANTES - TRATAMENTO CIRÚRGICO PROTESE NACIONAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0415', 'ARTROPLASTIA TOTAL DO QUADRIL PROTESE IMPORTADA CIMENTADA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0416', 'ARTROPLASTIA TOTAL DO QUADRIL PROTESE IMPORTADA SEM CIMENTO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0417', 'ARTROPLASTIA TOTAL DO QUADRIL PROTESE NACIONAL CIMENTADA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0418', 'ARTROPLASTIA TOTAL DO QUADRIL PROTESE NACIONAL SEM CIMENTO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0419', 'AUTOTRANSPLANTE CONJUNTIVAL OU RECOBRIMENTO CONJUNTIVAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0420', 'AUTOTRANSPLANTE CONJUNTIVAL OU RECOBRIMENTO CONJUNTIVAL - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0421', 'BIÓPSIA DE CONJUNTIVA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0422', 'BIÓPSIA DE PÁLPEBRA (INCISIONAL)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0423', 'BIÓPSIA DE PÁLPEBRA (INCISIONAL) - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0424', 'BIOPSIA EM MARGENS DE LESOES DE PELE E PEQUENOS TUMORES', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0425', 'BIOPSIA EM PECA CIRURGICA SIMPLES OU PELE', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0426', 'BIÓPSIA INCISIONAL DE MAMA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0427', 'BIOPSIA PERCUTÂNEA DE FRAGMENTO MAMÁRIO (CORE BIOPSY) ORIENTADA POR USG OU RX-AGULHA GROSSA (REAJUSTADO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0428', 'BIOPSIA SIMPLES POR LESAO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0429', 'BIOPSIA SIMPLES POR LESÃO - ANTRO E CORPO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0430', 'BLEFAROPLASTIA SUPERIOR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0431', 'BÓCIO MERGULHANTE: EXTIRPAÇÃO POR ACESSO CÉRVICO-TORÁCICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0432', 'BOLSA DE SANGUE', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0433', 'CANTOPLASTIA LATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0434', 'CANTOPLASTIA MEDIAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0435', 'CANTOPLASTIA MEDIAL - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0436', 'CAPSULECTOMIA POSTERIOR CIRÚRGICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0437', 'CAPSULECTOMIA POSTERIOR CIRÚRGICA POR VITREOFAGO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0438', 'CAPSULECTOMIA POSTERIOR CIRURGICA POR VITRÓFAGO - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0439', 'CAPSULOTOMIA A YAG LASER (CADA OLHO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0440', 'CAPSULOTOMIA A YAG LASER (CADA OLHO) (COMPLEMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0441', 'CAPSULOTOMIA A YAG LASER (CADA OLHO) (SIGTAP)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0442', 'CAPSULOTOMIA MONOCULAR LASER - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0443', 'CIMENTO SEM ANTIBIÓTICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0444', 'CIRURGIA BARIÁTRICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0445', 'CIRURGIA ESTERILIZADORA MASCULINA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0446', 'CISTO SACRO-COCCÍGEO - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0447', 'CISTO SINOVIAL - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0448', 'COLANGIOPANCREATOGRAFIA RETRÓGRADA ENDOSCÓPICA + PAPILOTOMIA ENDOSCÓPICA (PARA RETIRADA DE CÁLCULOS COLEDOCIANOS OU DRENAGEM BILIAR)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0449', 'COLECISTECTOMIA COM COLANGIOGRAFIA POR VIDEOLAPAROSCOPIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0450', 'COLECISTECTOMIA SEM COLANGIOGRAFIA POR VIDEOLAPAROSCOPIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0451', 'COLETA DE FLUXO PAPILAR DE MAMA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0452', 'COLOCAÇÃO CIRÚRGICA DE DUPLO J UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0453', 'COLOCAÇÃO URETEROSCÓPICA DE DUPLO J UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0454', 'COMPONENTE FEMORAL CIMENTADO MODULAR PRIMÁRIO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0455', 'CORREÇÃO CIRÚRGICA DE LAGOFTALMO-PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0456', 'CORREÇÃO CIRÚRGICA DE EPICANTO E TELECANTO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0457', 'CORREÇÃO CIRÚRGICA DE HÉRNIA DE ÍRIS', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0458', 'CORREÇÃO CIRÚRGICA DE HERNIA DE IRIS- PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0459', 'CORREÇÃO CIRÚRGICA DE LAGOFTALMO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0460', 'CORREÇÃO DE ENTRÓPIO E ECTRÓPIO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0461', 'CORREÇÃO DE ENTRÓPIO E ECTRÓPIO - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0462', 'CORREÇÃO DE INVERSÃO PAPILAR - UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0463', 'CRIOTERAPIA OCULAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0464', 'CRIOTERAPIA OCULAR - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0465', 'DACRIOCISTORRINOSTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0466', 'DACRIOCISTORRINOSTOMIA - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0467', 'DESCOMPRESSÃO MEDULAR E/OU CAUDA EQUINA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0468', 'DIARIA CASA DE APOIO (ATUALIZADA)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0469', 'DIARIA CTI', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0470', 'DIARIA DE UNIDADE DE TERAPIA INTENSIVA (UTI INFANTIL)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0471', 'DIÁRIA DE UNIDADE DE TERAPIA INTENSIVA ADULTO (UTI II) - 01 DIÁRIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0472', 'DIARIA HOSPITALAR LEITO CLINICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0473', 'DOENÇA DE PEYRONIE - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0474', 'DRENAGEM DE ABSCESSO DE MAMA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0475', 'DRENAGEM DE ABSCESSO DE PALPEBRA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0476', 'ENDOMETRIOSE PERITONEAL - TRATAMENTO CIRÚRGICO VIA LAPAROSCÓPICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0477', 'ENUCLEAÇÃO DE GLOBO OCULAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0478', 'EPIDIDIMECTOMIA UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0479', 'EPILAÇÃO A LASER', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0480', 'EPILAÇÃO A LASER - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0481', 'EPILAÇÃO DE CÍLIOS', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0482', 'EPILAÇÃO DE CÍLIOS - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0483', 'ESCLEROTERAPIA KIYOMITSU', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0484', 'EVISCERAÇÃO DE GLOBO OCULAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0485', 'EXCISAO E SUTURA DE LESAO NA PELE C/ PLASTICA EM Z OU ROTACAO DE RETALHO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0486', 'EXÉRESE DE CALÁZIO E OUTRAS PEQUENAS LESÕES DA PÁLPEBRA E SUPERCÍLIOS', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0487', 'EXERESE DE CALAZIO E OUTRAS PEQUENAS LESOES DA PALPEBRA E SUPERCILIOS - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0488', 'EXÉRESE DE CISTO VAGINAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0489', 'EXÉRESE DE LESÃO DA MAMA POR MARCAÇÃO ESTEREOTÁXICA OU ROLL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0490', 'EXÉRESE DE MAMA SUPRA-NUMERÁRIA - UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0491', 'EXÉRESE DE NÓDULO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0492', 'EXÉRESE DE TUMOR DE CONJUNTIVA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0493', 'EXÉRESE DE TUMOR DE CONJUNTIVAL (PN)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0494', 'EXÉRESE DE TUMOR DE PÁLPEBRA - RESSECÇÃO DE TUMOR PALPEBRAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0495', 'EXÉRESE DE TUMOR DE PÁLPEBRA - RESSECÇÃO DE TUMOR PALPEBRAL - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0496', 'EXPLANTE DE LENTE INTRA-OCULAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0497', 'EXPLANTE DE LENTE INTRA-OCULAR - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0498', 'EXPLORAÇÃO/DESCOMPRESSÃO TOTAL/PARCIAL DO NERVO FACIAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0499', 'FACOEMULSIFICAÇÃO COM IMPLANTE DE LENTE INTRA OCULAR DOBRAVEL - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0500', 'FACOEMULSIFICACAO COM IMPLANTE DE LENTE INTRA-OCULAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0501', 'FACOEMULSIFICACAO COM IMPLANTE DE LENTE INTRA-OCULAR DOBRAVEL INCLUINDO CONSULTA PRÉ E PÓS CIRURGICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0502', 'FISIOTERAPIA MOTORA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0503', 'FISIOTERAPIA RESPIRATÓRIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0504', 'FISSURECTOMIA COM OU SEM ESFINCTEROTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0505', 'FISTULECTOMIA ANORRETAL COM ABAIXAMENTO MUCOSO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0506', 'FISTULECTOMIA DE MAMA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0507', 'FOTOCOAGULAÇÃO A LASER', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0508', 'FOTOCOAGULAÇÃO A LASER - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0509', 'FOTOTRABECULOPLASTIA MONUCULAR A LASER - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0510', 'FOTOTRABECULOPLASTIA A LASER', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0511', 'FRATURA E OU LUXAÇÕES (INCLUINDO DESLOCAMENTO EPIFISÁRIO COTOVELO - PUNHO - TRATAMENTO CIRÚRGICO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0512', 'FRENOTOMIA LINGUAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0513', 'GASTROPLASTIA PARA OBESIDADE MÓRBIDA POR VIDEOLAPAROSCOPIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0514', 'GINECOMASTIA - UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0515', 'HALLUX VALGUS (UM PÉ) - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0516', 'HEMORRÓIDAS - LIGADURA ELÁSTICA (POR SESSÃO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0517', 'HÉRNIA DE DISCO TÓRACO-LOMBAR - TRATAMENTO CIRURGICO + DESCOMPRESSÃO MEDULAR E/OU CAUDA EQUINA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0518', 'HERNIORRAFIA INGUINAL - BILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0519', 'HERNIORRAFIA INGUINAL ENCARCERADA - BILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0520', 'HERNIORRAFIA INGUINAL NO RN OU LACTENTE', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0521', 'HERNIORRAFIA RECIDIVANTE', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0522', 'HERNIORRAFIA SEM RESSECÇÃO INTESTINAL ENCARCERADA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0523', 'HIPOSPADIA - POR ESTÁGIO - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0524', 'HIPOSPADIA DISTAL - TRATAMENTO EM 1 TEMPO - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0525', 'HISTERECTOMIATOTAL LAPAROSCÓPICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0526', 'HISTEROSCOPIA CIRÚRGICA COM BIÓPSIA E/OU CURETAGEM UTERINA, LISE DE SINÉQUIAS, RETIRADA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0527', 'HISTEROSCOPIA COM RESSECTOSCÓPIO PARA MIOMECTOMIA, POLIPECTOMIA, METROPLASTIA, END', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0528', 'HOSPEDAGEM COM PERNOITE', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0529', 'HOSPEDAGEM SEM PERNOITE', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0530', 'IMPLANTE SECUNDÁRIO DE LENTE INTRA-OCULAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0531', 'IMPLANTE SECUNDARIO DE LENTE INTRA-OCULAR - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0532', 'INFILTRAÇÃO SUBCONJUNTIVAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0533', 'INJEÇÃO ANTIANGIOGÊNICA DE TRIANCINOLONA (INCLUI MEDICAMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0534', 'INJEÇÃO DE GÁS INTRA-OCULAR (SF6 OU C3F8)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0535', 'INJEÇÃO INTRAVÍTREA (SEM A MEDICAÇÃO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0536', 'INJEÇÃO INTRAVÍTREA (SEM A MEDICAÇÃO) - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0537', 'INJECAO INTRAVITREO DE OZOURDEX - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0538', 'INJEÇÃO MONOCULAR ANTIANGIOGÊNICA DE AVASTIN (INCLUI MEDICAMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0539', 'INJEÇÃO MONOCULAR ANTIANGIOGÊNICA DE AVASTIN (INCLUI MEDICAMENTO) - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0540', 'INJEÇÃO MONOCULAR ANTIANGIOGÊNICA DE EYLIA (INCLUI MEDICAMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0541', 'INJEÇÃO MONOCULAR ANTIANGIOGÊNICA DE EYLIA (INCLUI MEDICAMENTO) - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0542', 'INJEÇÃO MONOCULAR ANTIANGIOGÊNICA DE LUCENTIS (INCLUI MEDICAMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0543', 'INJEÇÃO MONOCULAR ANTIANGIOGÊNICA DE LUCENTIS (INCLUI MEDICAMENTO) - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0544', 'INJEÇÃO MONOCULAR INTRAVÍTREA (MEDICAÇÃO COM O PACIENTE)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0545', 'INJEÇÃO MONOCULAR INTRAVÍTREA DE OZURDEX (INCLUI MEDICAMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0546', 'IRIDECTOMIA A YAG LASER (CADA OLHO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0547', 'IRIDECTOMIA CIRURGICA - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0548', 'IRIDOTOMIA A YAG LASER (CADA OLHO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0549', 'IRIDOTOMIA MONOCULAR LASER - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0550', 'IRODOTOMIA LASER MONOCULAR (PONTE NOVA)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0551', 'LAPAROSCOPIA GINECOLÓGICA COM OU SEM BIÓPSIA (INCLUI A CROMOTUBAGEM)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0552', 'LESÃO ANAL - ELETROCAUTERIZAÇÃO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0553', 'LINFADENECTOMIA AXILAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0554', 'MAMOPLASTIA REDUTORA SEM SILICONE', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0555', 'MANIPULAÇÃO ARTICULAR SOB ANESTESIA GERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0556', 'MASTECTOMIA RADICAL OU RADICAL MODIFICADA - QUALQUER TÉCNICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0557', 'MASTECTOMIA SIMPLES', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0558', 'MASTECTOMIA SUBCUTÂNEA E INCLUSÃO DA PRÓTESE', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0559', 'MASTOIDECTOMIA: TIMPANOMASTOIDECTOMIA+EXPLORAÇÃO E DESCOMPRESSÃODO NERVO FACIAL+ESTENOSE CONDUTO AUDITIVO EXTERNO (CANALPLASTIA)+ RESSECÇÃO DO OSSO TEMPORAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0560', 'MASTOPLASTIA EM MAMA OPOSTA APÓS RECONSTRUÇÃO DA CONTRALATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0561', 'MENISCECTOMIA - UM MENISCO - PROCEDIMENTO VIDEOARTROSCÓPICO DE JOELHO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0562', 'MICRONEURÓLISE MÚLTIPLAS', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0563', 'MIOMECTOMIA UTERINA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0564', 'NEFRECTOMIA RADICAL LAPAROSCÓPICA UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0565', 'NEFROLITOTRIPSIA PERCUTÂNEA UNILATERAL (MEC., E.H., OU US)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0566', 'NEFROLITOTRIPSIA PERCUTÂNEA UNILATERAL (MEC., E.H., OU US) + URETERORRENOLITOTRIPSIA FLEXÍVEL A LASER UNILATERAL + COLOCAÇÃO URETEROSCÓPICA DE DUPLO J - UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0567', 'NEFROLITOTRIPSIA PERCUTÂNEA UNILATERAL (PNEUMÁTICO-BALÍSTICA - MEC., ELETROHIDRÁULICA - E.H., OU ULTRASSOM - US) + URETERORRENOLITOTRIPSIA FLEXÍVEL A LASER UNILATERAL + COLOCAÇÃO URETEROSCÓPICA DE DUP', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0568', 'NEFROLITOTRIPSIA PERCUTÂNEA UNILATERAL(MEC.,E.H., OU US) + COLOCAÇÃO URETEROSCÓPICA DE DUPLO J - UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0569', 'ÓCULOS COM LENTES CORRETIVAS- MIGUILIM', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0570', 'OOFORECTOMIA LAPAROSCÓPICA UNI OU BILATERAL OU OOFOROPLASTIA UNI OU BILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0571', 'OOFRECTOMIA/ OOFOROPLASTIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0572', 'OPME P/ANGIOPLASTIA COM IMPLANTE DE DOIS STENT', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0573', 'OPME P/ANGIOPLASTIA COM IMPLANTE DE STENT', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0574', 'OPME P/ANGIOPLASTIA CORONARIANA PRIMÁRIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0575', 'OPME P/ANGIOPLASTIA SEM IMPLANTE DE STENT', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0576', 'ORBITOTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0577', 'ORQUIECTOMIA UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0578', 'PAAF DE MAMA - PUNÇÃO ASPIRATIVA DE MAMA POR AGULHA FINA (GUIADA POR ULTRASSONOGRAFIA)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0579', 'PAAF DE MAMA - PUNÇÃO ASPIRATIVA DE MAMA POR AGULHA FINA (GUIADA POR ULTRASSONOGRAFIA) (COMPLEMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0580', 'PAAF DE MAMA - PUNÇÃO ASPIRATIVA DE MAMA POR AGULHA FINA (GUIADA POR ULTRASSONOGRAFIA) (SIGTAP)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0581', 'PAAF TIREÓIDE - PUNÇÃO OU BIÓPSIA PERCUTANIA POR AGULHA FINA DA TIREÓIDE (GUIADA POR ULTRASSONOGRAFIA)(REAJUSTADO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0582', 'PAAF TIREÓIDE - PUNÇÃO OU BIÓPSIA PERCUTANIA POR AGULHA FINA DA TIREÓIDE (GUIADA POR ULTRASSONOGRAFIA)(REAJUSTADO) (COMPLEMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0583', 'PAAF TIREÓIDE - PUNÇÃO OU BIÓPSIA PERCUTANIA POR AGULHA FINA DA TIREÓIDE (GUIADA POR ULTRASSONOGRAFIA)(REAJUSTADO) (SIGTAP)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0584', 'PARTO IHNSD', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0585', 'PÉ PLANO/ PÉ CAVO/ COALISÃO TARSAL - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0586', 'PÉ TORTO CONGÊNITO (UM PÉ) - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0587', 'PIELOPLASTIA LAPAROSCÓPICA UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0588', 'PLÁSTICA DE CONJUNTIVA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0589', 'PLÁSTICA DE CONJUNTIVA PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0590', 'PLASTICA MAMARIA FEMININA NÃO ESTETICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0591', 'POLIPECTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0592', 'PROSTATAVESICULECTOMIA RADICAL + LINFADENECTOMIA PÉLVICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0593', 'PROSTATAVESICULECTOMIA RADICAL LAPAROSCÓPICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0594', 'PROSTATAVESICULECTOMIA RADICAL LAPAROSCÓPICA + LINFADENECTOMIA PÉLVICA LAPAROSCÓPICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0595', 'PROSTATECTOMIA A CÉU ABERTO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0596', 'PROSTATECTOMIA A CÉU ABERTO + TUMOR VESICAL - RESSECÇÃO ENDOSCÓPICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0597', 'PRÓTESE PARCIAL DE QUADRIL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0598', 'PULSOTERAPIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0599', 'PUNÇÃO LOMBAR COM ANALISE DE LIQUOR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0600', 'PUNÇÃO LOMBAR COM PRESSÃO DE ABERTURA E ANALISE DE LIQUOR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0601', 'PUNÇÃO PARA BIOPSIA/ASPIRATIVA DE ORGÃO OU ESTRUTURA ORIENTADA POR RX, US, CT (BIOPSIA FIGADO, RIM)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0602', 'QUADRANTECTOMIA - RESSECÇÃO SEGMENTAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0603', 'QUADRANTECTOMIA E LINFADENECTOMIA AXILAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0604', 'RECONSTITUIÇÃO DE CANAL LACRIMAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0605', 'RECONSTITUIÇÃO DE CAVIDADE ORBITÁRIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0606', 'RECONSTITUIÇÃO DE FUNDO DE SACO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0607', 'RECONSTITUIÇÃO PARCIAL DE PÁLPEBRA COM TARSORRAFIA OU BLEFARORRAFIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0608', 'RECONSTITUIÇÃO TOTAL DE PÁLPEBRA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0609', 'RECONSTRUÇÃO DA MAMA COM PRÓTESE E/OU EXPANSOR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0610', 'RECONSTRUÇÃO DE CÂMARA ANTERIOR DO OLHO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0611', 'RECONSTRUÇÃO, RETENCIONAMENTO OU REFORÇO DO LIGAMENTO CRUZADO ANTERIOR OU POSTERIOR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0612', 'RECONSTRUÇÃO, RETENCIONAMENTO OU REFORÇODO LIGAMENTO CRUZADO ANTERIOR OU POSTERIOR (PROCEDIMENTO VIDEOARTROSCÓPICO DE JOELHO) + REPARO OU SUTURA DE UM MENISCO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0613', 'REFLUXO GASTROESOFÁGICO-TRAT CIRÚRGICO(HERNIA DE HIATO)P/ VIDEOLAPAROSCOPIA+COLECISTECTOMIA SEM COLLANGIOGRAFIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0614', 'REMOÇÃO DE ÓLEO DE SILICONE', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0615', 'REMOÇÃO DE ÓLEO DE SILICONE - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0616', 'REPARO OU SUTURA DE UM MENISCO - PROCEDIMENTO VIDEOARTROSCÓPICO DE JOELHO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0617', 'REPARO OU SUTURA DE UM MENISCO (PROCEDIMENTO VIDEOARTROSCÓPICO DE JOELHO) + CONDROPLASTIA (COM REMOÇÃO DE CORPOS LIVRES) (PROCEDIMENTO VIDEOARTROSCÓPICO DE JOELHO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0618', 'REPOSICIONAMENTO DE LENTE INTRA-OCULAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0619', 'REPOSICIONAMENTO DE LENTE INTRA-OCULAR (PONTE NOVA)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0620', 'RESSECÇÃO DO LINFONODO SENTINELA/ TORÁCICA LATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0621', 'RESSECÇÃO DOS DUCTOS PRINCIPAIS DA MAMA - UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0622', 'RESSECÇÃO ENDOSCÓPICA DA PRÓSTATA + URETROTOMIA INTERNA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0623', 'RETINOPEXIA COM INTROFLEXÃO ESCLERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0624', 'RETINOPEXIA COM INTROFLEXÃO ESCLERAL (PONTE NOVA)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0625', 'RETIRADA DE CORPO ESTRANHO DA CÓRNEA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0626', 'RETIRADA ENDOSCÓPICA DE CÁLCULO DE URETER UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0627', 'RETIRADA ENDOSCÓPICA DE DUPLO J', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0628', 'RETRAÇÃO PALPEBRAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0629', 'RINOSSEPTOPLASTIA FUNCIONAL + TURBINECTOMIA OU TURBINOPLASTIA - BILATERAL + CORNETO INFERIOR - CAUTERIZAÇÃO LINEAR - BILATERAL + SINUSECTOMIA MAXILAR - VIA ENDONASAL X 2 + ETMOIDECTOMIAINTRANASAL X 2', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0630', 'RINOSSEPTOPLASTIA FUNCIONAL + TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL + CORNETO INFERIOR - CAUTERIZAÇÃO LINEAR- UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0631', 'RINOSSEPTOPLASTIA FUNCIONAL + TURBINECTOMIA OU TURBINOPLASTIA - UNILATERAL X 2 + CORNETO INFERIOR - CAUTERIZAÇÃO LINEAR- UNILATERAL X 2 + ADENO-AMIGDALECTOMIA X 2', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0632', 'RIZOTOMIA PERCUTÂNEA POR SEGMENTO - QUALQUER MÉTODO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0633', 'RUPTURA DO MANGUITO ROTADOR - PROCEDIMENTO VIDEOARTROSCÓPICO DE OMBRO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0634', 'RUPTURA DO MANGUITO ROTADOR (PROCEDIMENTO VIDEOARTROSCÓPICO DE OMBRO) + SINOVECTOMIA TOTAL (PROCEDIMENTO VIDEOARTROSCÓPICO DE OMBRO) + + TENOTOMIA DA PORÇÃO LONGA DOBÍCEPS (PROCEDIMENTO VIDEOARTROSCÓP', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0635', 'SALPINGECTOMIA UNI OU BILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0636', 'SEDAÇÃO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0637', 'SEDAÇÃO (COMPLEMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0638', 'SEDAÇÃO (SIGTAP)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0639', 'SEPTOPLASTIA (COM TURBINOPLASTIA)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0640', 'SEPTOPLASTIA PARA CORREÇÃO DE DESVIO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0641', 'SETORECTOMIA / QUADRANTECTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0642', 'SIMBLEFAROPLASTIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0643', 'SIMBLEFAROPLASTIA (PONTE NOVA)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0644', 'SINEQUIOTOMIA CIRÚRGICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0645', 'SINUSECTOMIA MAXILAR - VIA ENDONASAL X 2 + ETMOIDECTOMIA INTRANASAL X 2+ SINUSOTOMIA ESFENOIDAL X 2 SINUSOTOMIA FRONTAL INTRANASAL POR VIDEOENDOSCOPIA X2', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0646', 'SINUSOTOMIA BILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0647', 'SINUSOTOMIA ESFENOIDAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0648', 'SINUSOTOMIA TRANSMAXILAR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0649', 'SONDAGEM DE VIAS LACRIMAIS', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0650', 'SONDAGEM DE VIAS LACRIMAIS - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0651', 'SUTURA DE CONJUNTIVA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0652', 'SUTURA DE CÓRNEA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0653', 'SUTURA DE ESCLERA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0654', 'SUTURA DE PÁLPEBRAS', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0655', 'TELA INORGANICA DE POLIPROPILENO PEQUENA (ATE 100 CM2)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0656', 'TENÓLISE/TENDONESE - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0657', 'TENOPLASTIA / ENXERTO DE TENDÃO - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0658', 'TENOPLASTIA / ENXERTO DE TENDÃO - TRATAMENTO CIRÚRGICO + TRANSPOSIÇÃO ÚNICA DE TENDÃO + OSTEOTOMIA OU PSEUDARTROSE DO TARSO E MÉDIO PÉ - TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0659', 'TIMPANOPLASTIA (UNI / BILATERAL)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0660', 'TIMPANOPLASTIA: TIMPANOPLASTIA COM RECONSTRUÇÃO DE CADEIA OSSICULAR + ESTENOSE CONDUTO AUDITIVO EXTERNO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0661', 'TIMPANOTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0662', 'TIREOIDECTOMIA PARCIAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0663', 'TRABECULECTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0664', 'TRABECULECTOMIA - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0665', 'TRABECULECTOMIA - PN (COMPLEMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0666', 'TRABECULECTOMIA - PN (SIGTAP)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0667', 'TRAQUELECTOMIA - AMPUTAÇÃO, CONIZAÇÃO - (COM OU SEM CIRURGIA DE ALTA FREQUÊNCIA / CAF)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0668', 'TRATAMENTO CIRÚRGICO DE PTERÍGIO - EXERESE DE PTERÍGIO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0669', 'TRATAMENTO CIRURGICO DE PTERIGIO - EXERESE DE PTERIGIO - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0670', 'TRATAMENTO CIRURGICO DE PTERIGIO - EXERESE DE PTERIGIO - PN (COMPLEMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0671', 'TRATAMENTO CIRURGICO DE PTERIGIO - EXERESE DE PTERIGIO - PN (SIGTAP)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0672', 'TRATAMENTO CIRÚRGICO DE PTERÍGIO - EXERESE DE PTERÍGIO (COMPLEMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0673', 'TRATAMENTO CIRÚRGICO DE PTERÍGIO - EXERESE DE PTERÍGIO (SIGTAP)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0674', 'TRATAMENTO CIRÚRGICO DE RETOCELE (COLPOPERINEOPLASTIA POSTERIOR)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0675', 'TRATAMENTO CIRÚRGICO DE ROTURA DO MENISCO COM MENISCECTOMIA PARCIAL/ TOTAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0676', 'TRATAMENTO CIRÚRGICO DE TRÍQUIASE ( PN) COM OU SEM ENXERTO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0677', 'TRATAMENTO CIRÚRGICO DE TRÍQUIASE COM OU SEM ENXERTO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0678', 'TRATAMENTO CIRURGICO DE XANTELASMA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0679', 'TRATAMENTO DA SÍNDROME COMPRESSIVA EM TÚNEL OSTEO-FIBROSO AO NÍVEL DO CARPO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0680', 'TRATAMENTO DE NECROSE AVASCULAR POR FORAGEM DE ESTAQUEAMENTO ASSOCIADA À NECROSE', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0681', 'TRATAMENTO DE PTOSE PALPEBRAL PN- CORREÇÃO DE PTOSE PALPEBRAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0682', 'TRATAMENTO DE PTOSE PALPEBRAL PN- CORREÇÃO DE PTOSE PALPEBRAL (COMPLEMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0683', 'TRATAMENTO DE PTOSE PALPEBRAL PN- CORREÇÃO DE PTOSE PALPEBRAL (SIGTAP)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0684', 'TRATAMENTO DE PTOSE PALPEBRAL - CORREÇÃO DE PTOSE PALPEBRAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0685', 'TRATAMENTO MICROCIRÚRGICO DAS NEUROPATIAS COMPRESSIVAS (TUMORAL, INFLAMATÓRIO, ETC.+ TENOPLASTIA / ENXERTO DE TENDÃO - TRATAMENTO CIRÚRGICO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0686', 'TRATAMENTO MICROCIRÚRGICO DAS NEUROPATIAS COMPRESSIVAS (TUMORAL, INFLAMATÓRIO, ETC)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0687', 'TUMOR ANORRETAL - RESSECÇÃO ANORRETAL, TRATAMENTO CIRÚRGICO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0688', 'TUMOR ÓSSEO (RESSECÇÃO SIMPLES)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0689', 'TUMOR VESICAL - RESSECÇÃO ENDOSCÓPICA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0690', 'TÚNEL DO CARPO - DESCOMPRESSÃO - PROCEDIMENTO VIDEOARTROSCÓPICO DE PUNHO E TÚNEL D', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0691', 'URETEROLITOTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0692', 'URETERORRENOLITOTRIPSIA FLEXÍVEL A LASER UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0693', 'URETERORRENOLITOTRIPSIA FLEXÍVEL UNILATERAL + COLOCAÇÃO URETEROSCÓPICA DE DUPLO J UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0694', 'URETERORRENOLITOTRIPSIA RÍGIDA UNILATERAL', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0695', 'URETERORRENOLITOTRIPSIA RÍGIDA UNILATERAL A LASER + COLOCAÇÃO URETEROSCÓPICA DE DUPLO J -', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0696', 'URETROTOMIA INTERNA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0697', 'URGENCIA/EMERGENCIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0698', 'VARIZES - TRATAMENTO CIRÚRGICO DE DOIS MEMBROS', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0699', 'VARIZES - TRATAMENTO CIRÚRGICO DE UM MEMBRO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0700', 'VITRECTOMIA ANTERIOR', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0701', 'VITRECTOMIA ANTERIOR - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0702', 'VITRECTOMIA ANTERIOR - PN (COMPLEMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0703', 'VITRECTOMIA ANTERIOR - PN (SIGTAP)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0704', 'VITRECTOMIA POSTERIOR COM INFUSÃO DE PERFLUOROCARBONO E ENDOLASER', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0705', 'VITRECTOMIA POSTERIOR COM INFUSÃO DE PERFLUOROCARBONO E ÓLEO DE SILICONE E ENDOLASER', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0706', 'VITRECTOMIA POSTERIOR E ÓLEO DE SILICONE E ENDOLASER - PN', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0707', 'VITRECTOMIA POSTERIOR E ÓLEO DE SILICONE E ENDOLASER - PN (COMPLEMENTO)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0708', 'VITRECTOMIA POSTERIOR E ÓLEO DE SILICONE E ENDOLASER - PN (SIGTAP)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0);

SELECT count(*) AS total_procedimentos_cadastrados FROM public.consultas_procedimentos;
