-- Migration: Seed procedimentos de consultas, exames e cirurgias
DROP POLICY IF EXISTS "Enable all access for consultas_procedimentos" ON public.consultas_procedimentos;
DROP POLICY IF EXISTS "Enable insert for all users" ON public.consultas_procedimentos;

CREATE POLICY "Enable all access for consultas_procedimentos" ON public.consultas_procedimentos
  FOR ALL USING (true) WITH CHECK (true);

DELETE FROM public.consultas_procedimentos;

INSERT INTO public.consultas_procedimentos (code, name, type, status, recurso, total_quantity, available_quantity)
VALUES
('0001', 'CLÍNICA GERAL', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0002', 'CARDIOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0003', 'PEDIATRIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0004', 'GINECOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0005', 'OBSTETRÍCIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0006', 'ORTOPEDIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0007', 'NEUROLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0008', 'NEUROCIRURGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0009', 'PSIQUIATRIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0010', 'PSICOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0011', 'DERMATOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0012', 'OFTALMOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0013', 'OTORRINOLARINGOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0014', 'PNEUMOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0015', 'ENDOCRINOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0016', 'GASTROENTEROLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0017', 'NEFROLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0018', 'REUMATOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0019', 'HEMATOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0020', 'ONCOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0021', 'INFECTOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0022', 'ALERGOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0023', 'GERIATRIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0024', 'NUTRIÇÃO', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0025', 'FISIOTERAPIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0026', 'FONOAUDIOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0027', 'TERAPIA OCUPACIONAL', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0028', 'CIRURGIA GERAL (CONSULTA)', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0029', 'CIRURGIA VASCULAR (CONSULTA)', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0030', 'CIRURGIA PLÁSTICA (CONSULTA)', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0031', 'MASTOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0032', 'PROCTOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0033', 'ANGIOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0034', 'COLOPROCTOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0035', 'ANESTESIOLOGIA (AVALIAÇÃO)', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0036', 'MEDICINA DO TRABALHO', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0037', 'MEDICINA ESPORTIVA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0038', 'GENÉTICA MÉDICA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0039', 'HOMEOPATIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0040', 'ACUPUNTURA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0041', 'ODONTOLOGIA', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0042', 'BUCOMAXILOFACIAL', 'Consulta', 'Ativo', 'Não Se Aplica', 0, 0),
('0043', 'HEMOGRAMA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0044', 'GLICEMIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0045', 'COLESTEROL', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0046', 'PSA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0047', 'TSH', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0048', 'T4', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0049', 'HIV', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0050', 'HEPATITES', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0051', 'URINA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0052', 'FEZES', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0053', 'RAIO-X', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0054', 'ULTRASSOM', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0055', 'DOPPLER', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0056', 'MAMOGRAFIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0057', 'TOMOGRAFIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0058', 'RESSONÂNCIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0059', 'PET-CT', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0060', 'CINTILOGRAFIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0061', 'ECG', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0062', 'ECOCARDIOGRAMA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0063', 'HOLTER', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0064', 'MAPA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0065', 'TESTE ERGOMÉTRICO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0066', 'EEG', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0067', 'ENMG', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0068', 'POTENCIAL EVOCADO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0069', 'ESPIROMETRIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0070', 'POLISSONOGRAFIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0071', 'OXIMETRIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0072', 'OCT', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0073', 'CAMPIMETRIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0074', 'TONOMETRIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0075', 'FUNDOSCOPIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0076', 'AUDIOMETRIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0077', 'BERA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0078', 'NASOFIBROSCOPIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0079', 'PAPANICOLAU', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0080', 'CARDIOTOCOGRAFIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0081', 'ESPERMOGRAMA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0082', 'FLUXOMETRIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0083', 'TESTE DO PEZINHO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0084', 'TESTE DO OLHINHO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0085', 'TESTE DO CORAÇÃOZINHO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0086', 'GASOMETRIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0087', 'CITOLOGIA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0088', 'ANATOMOPATOLÓGICO', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0089', 'EXAMES GENÉTICOS', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0090', 'CULTURA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0091', 'ANTIBIOGRAMA', 'Exame', 'Ativo', 'Não Se Aplica', 0, 0),
('0092', 'ENDOSCOPIA DIGESTIVA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0093', 'COLONOSCOPIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0094', 'RETOSSIGMOIDOSCOPIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0095', 'HISTEROSCOPIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0096', 'CISTOSCOPIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0097', 'PELE', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0098', 'MAMA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0099', 'PRÓSTATA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0100', 'FÍGADO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0101', 'RIM', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0102', 'PUNÇÃO ASPIRATIVA (PAAF)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0103', 'CATETERISMO CARDÍACO', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0104', 'PUNÇÃO LOMBAR (LÍQUOR)', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0105', 'CATARATA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0106', 'HERNIOPLASTIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0107', 'COLECISTECTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0108', 'VASECTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0109', 'LAQUEADURA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0110', 'POSTECTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0111', 'APENDICECTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0112', 'HISTERECTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0113', 'ARTROSCOPIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0114', 'AMIGDALECTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0115', 'ADENOIDECTOMIA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0116', 'CESARIANA', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0117', 'EXÉRESE DE TUMORES', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0118', 'CIRURGIAS VASCULARES', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0119', 'CIRURGIAS ORTOPÉDICAS', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0120', 'CIRURGIAS UROLÓGICAS', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0121', 'CIRURGIAS PLÁSTICAS', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0),
('0122', 'CIRURGIAS BUCOMAXILOFACIAIS', 'Cirurgia', 'Ativo', 'Não Se Aplica', 0, 0);
